---
- name: Set container facts
  ansible.builtin.set_fact:
    container: "{{ container_defaults | combine(service.container) | combine({'name': service.container.name | default(service.name)}) }}"

- name: Ensure app_data directory exists
  become: true
  delegate_to: "{{ service.host }}"
  ansible.builtin.file:
    path: "/opt/data/{{ service.name }}"
    state: directory
    mode: 0755

- name: Create Docker container
  become: true
  delegate_to: "{{ service.host }}"
  community.docker.docker_container: "{{ container }}"

