---
- name: Copy data to remote host
  become: true
  when: item.src is defined or item.content is defined
  block:
    - name: Check source file
      when: item.src is defined
      block:
        - name: Set local file facts for {{ item.src }}
          ansible.builtin.set_fact:
            src_file: "{{ ansible_root + '/services/data/' + item.src }}"
            src_ext: "{{ item.src | splitext }}"
          when: item.src is defined

        - name: Get local file stats for {{ src_file }}
          ansible.builtin.stat:
            path: "{{ src_file }}"
          become: false
          register: file_stat
          delegate_to: localhost
          no_log: true

        - name: Fail if local file does not exist
          ansible.builtin.fail:
            msg: "File {{ src_file }} does not exist"
          when: file_stat.stat.exists is false

    - name: Ensure destination dir exists
      file:
        path: "{{ item.dest | dirname }}"
        owner: "{{ item.dir_owner | default(omit) }}"
        group: "{{ item.dir_group | default(omit) }}"
        mode: "{{ item.dir_mode | default('0700') }}"
        state: directory

    - name: Copy file over
      ansible.builtin.copy:
        src: "{{ src_file | default(omit) }}"
        content: "{{ item.content | default(omit) }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: "{{ item.mode | default(omit) }}"
        force: "{{ item.force | default(true) }}"
      when: src_ext[1] != '.j2'

    - name: Copy template over
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: "{{ item.mode | default(omit) }}"
        force: "{{ item.force | default(true) }}"
      when: src_ext[1] == '.j2'

- name: Create empty file or directory
  become: true
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: "{{ item.state | default('directory') }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    recurse: "{{ true if (item.state is undefined or item.state == 'directory') else omit }}"
  when:
    - item.src is not defined
    - item.content is not defined
