---
- name: Copy data to remote host
  become: true
  delegate_to: "{{ service.host }}"
  when: file.src is defined or file.content is defined
  block:
    - name: Check source file
      when: file.src is defined
      block:
        - name: Set local file facts for {{ item.src }}
          ansible.builtin.set_fact:
            src_file: "{{ ansible_root + '/services/data/' + file.src }}"
            src_ext: "{{ file.src | splitext }}"
          when: file.src is defined

        - name: Get local file stats for {{ src_file }}
          ansible.builtin.stat:
            path: "{{ src_file }}"
          become: false
          register: file_stat
          delegate_to: localhost
          no_log: true

        - name: Fail if local file does not exist
          ansible.builtin.fail:
            msg: "File {{ src_file }} does not exist"
          when: file_stat.stat.exists is false

    - name: Ensure destination dir exists
      file:
        path: "{{ file.dest | dirname }}"
        owner: "{{ file.dir_owner | default(omit) }}"
        group: "{{ file.dir_group | default(omit) }}"
        mode: "{{ file.dir_mode | default('0755') }}"
        state: directory

    - name: Copy file over
      ansible.builtin.copy:
        src: "{{ src_file | default(omit) }}"
        content: "{{ file.content | default(omit) }}"
        dest: "{{ file.dest }}"
        owner: "{{ file.owner | default(omit) }}"
        group: "{{ file.group | default(omit) }}"
        mode: "{{ file.mode | default(omit) }}"
        force: "{{ file.force | default(true) }}"
      when: src_ext[1] != '.j2' and not file_stat.stat.isdir

    - name: Copy directory contents
      ansible.builtin.copy:
        src: "{{ src_file }}/"
        dest: "{{ file.dest }}"
        owner: "{{ file.owner | default(omit) }}"
        group: "{{ file.group | default(omit) }}"
        mode: "{{ file.mode | default(omit) }}"
        force: "{{ file.force | default(true) }}"
      when: file_stat.stat.isdir

    - name: Copy template over
      ansible.builtin.template:
        src: "{{ src_file }}"
        dest: "{{ file.dest }}"
        owner: "{{ file.owner | default(omit) }}"
        group: "{{ file.group | default(omit) }}"
        mode: "{{ file.mode | default(omit) }}"
        force: "{{ file.force | default(true) }}"
      when: src_ext[1] == '.j2'

- name: Create empty file or directory
  become: true
  delegate_to: "{{ file.host }}"
  ansible.builtin.file:
    path: "{{ file.dest }}"
    state: "{{ file.state | default('directory') }}"
    mode: "{{ file.mode | default(omit) }}"
    owner: "{{ file.owner | default(omit) }}"
    group: "{{ file.group | default(omit) }}"
    recurse: "{{ true if (file.state is undefined or file.state == 'directory') else omit }}"
  when:
    - file.src is not defined
    - file.content is not defined
