---
- name: Load configs
  tags: [always]
  no_log: true
  ansible.builtin.include_vars:
    dir: "{{ ansible_root }}/services"
    ignore_unknown_extensions: true
    depth: 1
    name: service_configs

- name: Run service tasks
  ansible.builtin.include_tasks: wrapper.yml
  loop: "{{ services }}"
