---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: v0.13.9
    valuesFile: values.yaml
    namespace: networking
    includeCRDs: true
    releaseName: metallb

resources:
  - namespace.yaml
  - metallb-config.yaml
