apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone

resources:
  - secrets/externalsecret-db.yaml
  - secrets/externalsecret-minio.yaml
  - secrets/externalsecret-drone.yaml
  - secrets/externalsecret-ssh.yaml
  - pg-cluster.yaml
