---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: drone-db
  namespace: drone
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3

  storage:
    size: 10Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: drone
      owner: drone
      secret:
        name: drone-db-secret

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
    pg_hba:
      - host all all 0.0.0.0/0 md5

  backup:
    barmanObjectStore:
      destinationPath: s3://drone/
      endpointURL: https://s3.sbbh.cloud
      s3Credentials:
        accessKeyId:
          name: drone-db-minio-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: drone-db-minio-secret
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
