---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: drone-db
  namespace: drone
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3

  storage:
    size: 10Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: drone
      owner: drone
      secret:
        name: drone-db-secret

  backup:
    barmanObjectStore:
      destinationPath: s3://drone/
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
