env:
  DRONE_SERVER_HOST: drone.k8s.sbbh.cloud
  DRONE_SERVER_PROTO: https
  DRONE_GITEA_SERVER: https://git.sbbh.cloud
  DRONE_USER_CREATE: username:sysadm,admin:true
  DRONE_GIT_ALWAYS_AUTH: true
  DRONE_DATABASE_DRIVER: postgres
  DRONE_REPO_BRANCH: main

extraSecretNamesForEnvFrom:
  - drone-secret

persistentVolume:
  enabled: false
