---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifest-apps
  namespace: gitops
spec:
  generators:
    - git:
        repoURL: https://git.sbbh.cloud/sysadm/homelab.git
        revision: main
        directories:
          - path: "k8s/apps/*/*"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{path.basenameNormalized}}"
    spec:
      project: default
      source:
        repoURL: https://git.sbbh.cloud/sysadm/homelab.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[2]}}"
      ignoreDifferences:
      - group: external-secrets.io
        kind: ExternalSecret
        jqPathExpressions:
          - .spec.dataFrom[].find
          - .spec.data[].remoteRef
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
