---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sops-age-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: sops-age-key

  data:
    - secretKey: key.txt
      remoteRef:
        key: ARGO_AGE_KEY

