fullnameOverride: argocd

configs:
  params:
    applicationsetcontroller.policy: "create-only"

# Enable Kustomize Alpha Plugins via Argo CD ConfigMap, required for ksops
server:
  replicas: 2
  config:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

controller:
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1

applicationSet:
  replicaCount: 2

repoServer:
  replicas: 2
  # Use init containers to configure custom tooling
  # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age-key

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.2.0
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv $GOPATH/bin/kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /.config/sops/age
      name: sops-age
  env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/key.txt
