---

k3s_version: v1.25.7+k3s1
kube_vip_tag_version: "v0.5.11"
metal_lb_speaker_tag_version: "v0.13.9"
metal_lb_controller_tag_version: "v0.13.9"

systemd_dir: /etc/systemd/system

flannel_iface: eth0
apiserver_endpoint: 10.0.10.70

# metallb ip range for load balancer
metal_lb_ip_range: "10.0.10.71-10.0.10.79"

k3s_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30393937623534343665353365643233353561303532316263306238373066363735343333396633
          3139616434336163343830353334343839646238303935350a633166646331333636336132313961
          64623262613138633235313466326438323331353132343535666230343931346466326131373830
          3261666161613964300a613834306362313962323335343163616439346233373833663464333864
          6562

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['workers'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}
  --resolv-conf /etc/k3s-resolv.conf

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
  --kube-controller-manager-arg bind-address=0.0.0.0
  --kube-proxy-arg metrics-bind-address=0.0.0.0
  --kube-scheduler-arg bind-address=0.0.0.0
  --etcd-expose-metrics true
  --kubelet-arg containerd=/run/k3s/containerd/containerd.sock

extra_agent_args: >-
  {{ extra_args }}
