---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone-secret
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: drone-secret

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
    - extract:
        key: DOCKER_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
    - extract:
        key: GIT_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
    - extract:
        key: RENOVATE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
