---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tmate-ssh-secret
  namespace: drone
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: tmate-ssh-secret
    template:
      engineVersion: v2
      data:
        ssh_host_ed25519_key: "{{ .SSH_KEY }}"
        ssh_host_ed25519.key.pub: "{{ .SSH_PUB_KEY }}"

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
