---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone-db-minio-secret
  namespace: drone
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: drone-db-minio-secret
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .MINIO_USER }}"
        ACCESS_SECRET_KEY: "{{ .MINIO_PASSWORD }}"

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
