---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.${DOMAIN}:8200"
      path: ops
      version: v2
      auth:
        kubernetes:
          mountPath: homelab
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
