---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault-tailscale.external-secrets.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: kube-system
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
        namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.sbbh.cloud:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: homelab
          role: external-secrets
          serviceAccountRef:
            name: external-secrets

