---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: vps.tailnet-7233.ts.net
  name: vault-tailscale
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
      protocol: TCP
