---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-gateway
spec:
  interval: 2h
  url: https://k8s-gateway.github.io/k8s_gateway
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-gateway
      version: 3.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: sbbh.cloud
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: 10.11.80.82
    ttl: 300
    watchedResources:
      - Gateway
      - HTTPRoute
      - TLSRoute
      - Service
    env:
      - name: LOG_LEVEL
        value: info
