kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repo-nfs-backups
  namespace: kasten-io
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
