kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: nfs-backup
  namespace: kasten-io
  managedFields:
    - manager: controllermanager-server
      operation: Update
      apiVersion: config.kio.kasten.io/v1alpha1
      fieldsType: FieldsV1
    - manager: dashboardbff-server
      operation: Update
      apiVersion: config.kio.kasten.io/v1alpha1
      fieldsType: FieldsV1
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: repo-nfs-backups
  type: Location
