---
borg_ssh_key: "{{ vault_ssh_keys.priv.borg }}"
borg_passphrase: "{{ vault_borg_passphrase }}"
borg_hc_ping_url_default: "{{ vault_borg_hc_ping_url_default }}"

borg_remote_path: /usr/local/bin/borg
borg_encryption_passphrase: "{{ borg_passphrase }}"
borg_server: "ssh://backup@{{ network_svc.nas.ip }}/volume1/backups/borg"
borg_ssh_command: "ssh -i ~/.ssh/borg"
borg_retention_policy:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 12
borgmatic_hooks:
  before_backup:
    - echo "$(date) - Starting backup."
  after_backup:
    - echo "$(date) - Backup created."
  on_error:
    - echo "$(date) - Error while creating a backup."
  healthchecks:
    ping_url: "{{ borg_hc_ping_url | default(borg_hc_ping_url_default) }}"
