---
crowdsec_port: "{{ network_svc.crowdsec.port }}"
crowdsec_hub: false

crowdsec_whitelist:
  ip:
    - "172.0.0.1"
  cidr:
    - "192.168.0.0/16"
    - "10.0.0.0/8"
    - "172.16.0.0/12"

crowdsec_mapquest_api: "{{ vault_crowdsec_mapquest_api }}"
crowdsec_discord_webhook_key: "{{ vault_crowdsec_discord_webhook_key }}"
