---
media_bazarr_api: "{{ vault_bazarr_api }}"
media_prowlarr_api: "{{ vault_prowlarr_api }}"
media_radarr_api: "{{ vault_radarr_api }}"
media_readarr_ebooks_api: "{{ vault_readarr_ebooks_api }}"
media_readarr_audiobooks_api: "{{ vault_readarr_audiobooks_api }}"
media_sonarr_api: "{{ vault_sonarr_api }}"
media_sabnzbd_api: "{{ vault_sabnzbd_api }}"
media_qbittorrent_pass: "{{ vault_qbittorrent_pass }}"
