---
net_domain:
  tld: sbbh.cloud
  tld_local: int.sbbh.cloud
  tld_test: test.sbbh.cloud
  tld_k8s: k8s.sbbh.cloud

net_cidr:
  lan: "10.11.0.0/16"
  servers: "10.11.10.0/24"
  dmz: "10.11.5.0/30"
  vms: "10.11.20.0/24"
  k8s: "10.11.80.0/24"
  tailscale: "100.64.0.0/10"
  docker:
    mesh: "192.168.100.0/24"
  all:
    [
      "127.0.0.1/32",
      "10.11.0.0/16",
      "192.168.0.0/16",
      "172.16.0.0/12",
      "100.64.0.0/10",
    ]

net_cloudflare_ips:
  [
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22",
  ]

net_hosts:
  gw: "{{ ansible_default_ipv4.gateway | default('') }}"
  opnsense: "{{ net_cidr.lan | ansible.utils.ipsubnet(24, -2) | ansible.utils.nthhost(1) }}"
  pikvm:
    ip: "{{ net_cidr.servers | ansible.utils.nthhost(254) }}"
  bastion:
    ip: "{{ net_cidr.dmz | ansible.utils.nthhost(2) }}"
    hwaddr: "b6:80:83:80:64:2b"
    node: pve-nuc
    vmid: 202
  nas:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(10) }}"
    hwaddr: "96:96:e4:b0:a1:8c"
    node: pve-nas
    vmid: 210
  pbs:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(20) }}"
    hwaddr: "0a:b9:3c:8f:96:b7"
    node: pve-nas
    vmid: 220
  media:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(30) }}"
    hwaddr: "32:63:bd:e4:e0:09"
    node: pve-nas
    vmid: 230
  services:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(40) }}"
    hwaddr: "f2:c4:78:b6:16:11"
    node: pve-nuc
    vmid: 240
  plex:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(50) }}"
    hwaddr: "6a:1b:53:c1:2f:d2"
    node: pve-nuc
    vmid: 250
  windows:
    ip: "{{ net_cidr.vms | ansible.utils.nthhost(90) }}"
    hwaddr: "aa:69:12:a3:17:bd"
    node: pve-nuc
    vmid: 290
  pve:
    pve_nas: "{{ net_cidr.servers | ansible.utils.nthhost(10) }}"
    pve_nuc: "{{ net_cidr.servers | ansible.utils.nthhost(11) }}"
    pve_opti_01: "{{ net_cidr.servers | ansible.utils.nthhost(12) }}"
    pve_opti_02: "{{ net_cidr.servers | ansible.utils.nthhost(13) }}"
  k8s:
    master_1: "{{ net_cidr.k8s | ansible.utils.nthhost(11) }}"
    master_2: "{{ net_cidr.k8s | ansible.utils.nthhost(12) }}"
    master_3: "{{ net_cidr.k8s | ansible.utils.nthhost(13) }}"
    worker_1: "{{ net_cidr.k8s | ansible.utils.nthhost(21) }}"
    worker_2: "{{ net_cidr.k8s | ansible.utils.nthhost(22) }}"
    worker_3: "{{ net_cidr.k8s | ansible.utils.nthhost(23) }}"
    api: "{{ net_cidr.k8s | ansible.utils.nthhost(80) }}"
    ingress: "{{ net_cidr.k8s | ansible.utils.nthhost(100) }}"

net_vpn:
  openvpn_user: "{{ vault_openvpn_user }}"
  openvpn_pass: "{{ vault_openvpn_pass }}"

net_svc:
  adguard:
    host: "{{ net_hosts.opnsense }}"
    port: "5380"
  authentik:
    host: bastion
    port: "9000"
  authentik_worker:
    host: bastion
  audiobookshelf:
    host: media
    port: "9060"
  bazarr:
    host: media
    port: "9053"
  calibre:
    host: media
    port: "9061"
    port_server: "9062"
  calibre_web:
    host: media
    port: "9063"
  changedetection:
    host: services
    port: "9033"
  changedetection_chrome:
    host: services
  crowdsec:
    host: bastion
    port: "9003"
  endlessh:
    host: bastion
  filebrowser:
    host: media
    port: "9027"
  flatnotes:
    host: services
    port: "9028"
  freshrss:
    host: services
    port: "9026"
  geoipupdate:
    host: bastion
  gitea:
    host: services
    port: "9023"
    port_ssh: "9022"
  gluetun:
    host: media
    ip: "192.168.100.100"
    port: "9005"
  jellyfin:
    host: plex
    port: "8096"
  linkace:
    host: services
    port: "9036"
  linx:
    host: services
    port: "9024"
  minio:
    host: services
    port: "9006"
    port_console: "9007"
  cockpit:
    host: nas
    port: "9090"
  openspeedtest:
    host: services
    port: "9031"
  overseerr:
    host: plex
    port: "9071"
  pbs:
    host: pbs
    port: "8007"
  pgadmin:
    host: services
    port: "9025"
  pikvm:
    host: pikvm
  plex:
    host: plex
    port: "32400"
  plex_meta_manager:
    host: plex
  portainer:
    host: services
    port: "9001"
    port_agent: "9002"
  portainer_agent_bastion:
    host: bastion
  portainer_agent_media:
    host: media
  portainer_agent_plex:
    host: plex
  postgres_bastion:
    host: bastion
    port: "5432"
  postgres_services:
    host: services
    port: "5432"
  prowlarr:
    host: media
    port: "9054"
  pve:
    host: none
    port: "8006"
  qbittorrent:
    host: media
    port: "9090"
  radarr:
    host: media
    port: "9050"
  readarr_ebooks:
    host: media
    port: "9055"
  readarr_audiobooks:
    host: media
    port: "9056"
  redis_bastion:
    host: bastion
  sabnzbd:
    host: media
    port: "9091"
  sonarr:
    host: media
    port: "9051"
  tautulli:
    host: plex
    port: "9070"
  threadfin:
    host: plex
    port: "9092"
    port_dvr: "1901"
  traefik:
    host: bastion
  unpackerr:
    host: media
  uptimekuma:
    host: bastion
    port: "9032"
  whoami:
    host: bastion
  wizarr:
    host: plex
    port: "9072"
