apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-admin
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: es-admin
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .adminUser }}"
        password: "{{ .adminPassword }}"
        roles: superuser

  dataFrom:
    - extract:
        key: EFK_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
