---

- name: Create postgres container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: postgres

- name: Create redis container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: redis

- name: Create authentik server container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: authentik_server

- name: Create authentik worker container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: authentik_worker

- name: Create authentik database
  ansible.builtin.command: docker exec postgres createdb -U {{ common_user }} authentik
  register: _postgres
  failed_when: "_postgres.rc != 0 and 'already exists' not in _postgres.stderr"
  changed_when: false
