apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  namespace: traefik
  repo: https://traefik.github.io/charts
  valuesFile: values.yaml
  version: v22.0.0
  includeCRDs: true

resources:
- namespace.yaml
- middlewares.yaml
- tlsstore.yaml
- ingress-route.yaml
