---
cluster:
  allowSchedulingOnControlPlanes: true
  apiServer:
    extraArgs:
      # https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/
      enable-aggregator-routing: true
      feature-gates: MutatingAdmissionPolicy=true
      runtime-config: admissionregistration.k8s.io/v1alpha1=true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  coreDNS:
    disabled: true
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
    advertisedSubnets:
      - 10.11.80.0/24
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  # Disable built-in CNI to use Cilium
  network:
    cni:
      name: none
  proxy:
    disabled: true
