---

- name: Copy SSH keys
  become: true
  no_log: "{{ debug is not defined | default(false) }}"
  ansible.builtin.copy:
    content: '{{ borg_ssh_key }}'
    dest: '/root/.ssh/borg'
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Run borgbackup role
  ansible.builtin.include_role:
    name: borgbase.ansible_role_borgbackup
