apprise:
  container:
    image: lscr.io/linuxserver/apprise-api:0.10.0
    volumes:
      - "{{ common_dir }}/apprise/config:/config"
    ports:
      - "{{ net_svc.apprise.port }}:8000"

  traefik:

  uptime:
    group: services
