---
borgmatic_nas:
  name: borgmatic
  container:
    image: ghcr.io/borgmatic-collective/borgmatic:1.8.10
    capabilities:
      - net_admin
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_backup_dir'] | default('') }}/borg:/mnt/repo"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_media_dir'] }}:/mnt/media:ro"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}:/mnt/app_data:ro"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}/borgmatic/etc:/etc/borgmatic.d"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}/borgmatic/state:/root/.borgmatic"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}/borgmatic/config:/root/.config/borg"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}/borgmatic/ssh:/root/.ssh"
      - "{{ hostvars[net_svc.borgmatic_nas.host]['common_dir'] }}/borgmatic/cache:/root/.cache/borg"
    env:
      BORG_PASSPHRASE: "{{ borg_encryption_passphrase }}"
      BORG_RSH: "ssh -i ~/.ssh/borg"
