---
filebrowser:
  container:
    image: filebrowser/filebrowser:v2.26.0
    ports:
      - "{{ net_svc.filebrowser.port }}:80"
    env:
      PUID: "1026"
      PGID: "101"
    volumes:
      - "{{ hostvars[net_svc.filebrowser.host]['common_dir'] }}/filebrowser/filebrowser.db:/database/filebrowser.db"
      - "{{ hostvars[net_svc.filebrowser.host]['common_dir'] }}/filebrowser/settings.json:/config/settings.json"
      - "{{ hostvars[net_svc.filebrowser.host]['common_media_dir'] }}:/srv"

  traefik:
    name: files
    rtr_middlewares:
      - chain-external-no-auth

  uptime:
    group: services
