flatnotes:
  container:
    image: dullage/flatnotes:v4.0.3
    ports:
      - "{{ net_svc.flatnotes.port }}:8080"
    volumes:
      - "{{ common_apps_dir }}/flatnotes/data:/data"
    env:
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "{{ common_user }}"
      FLATNOTES_PASSWORD: "{{ vault_flatnotes_pass }}"
      FLATNOTES_SECRET_KEY: "{{ vault_flatnotes_key }}"

  traefik:
    name: notes

  uptime:
    group: services
