---
nextcloud:
  container:
    image: nextcloud:28.0.1
    hostname: "next.{{ net_domain.tld }}"
    ports:
      - "{{ net_svc.nextcloud.port }}:80"
    volumes:
      - "{{ common_dir }}/nextcloud/html:/var/www/html"
      - "{{ common_data_dir }}"
    env:
      POSTGRES_DB: "nextcloud"
      POSTGRES_HOST: "postgres:5432"
      POSTGRES_USER: "{{ common_user }}"
      POSTGRES_PASSWORD: "{{ postgres_pass }}"

      NEXTCLOUD_ADMIN_USER: "{{ common_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_pass }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "next.{{ net_domain.tld }}"
      TRUSTED_PROXIES: "{{ net_svc.bastion.ip }}"
      OVERWRITEHOST: "next.{{ net_domain.tld }}"
      OVERWRITEPROTOCOL: "https"
      SMTP_HOST: "{{ common_email_server }}"
      SMTP_SECURE: "{{ common_email_protocol }}"
      SMTP_PORT: "{{ common_email_port | string }}"
      SMTP_NAME: "{{ common_email_user }}"
      MAIL_FROM_ADDRESS: "{{ common_email_svc }}"
      SMTP_PASSWORD: "{{ common_email_pass }}"

  traefik:
    routers:
      - name: "nextcloud"
        rule: "Host(`next.{{ net_domain.tld }}`)"
        middlewares:
          - nextcloud-secure-headers
          - nextcloud-redirect
          - crowdsec-bouncer
          - rate-limit
    middlewares: |
      nextcloud-secure-headers:
        headers:
          accessControlMaxAge: 100
          sslRedirect: true
          stsSeconds: 63072000
          stsIncludeSubdomains: true
          stsPreload: true
          forceSTSHeader: true
          customFrameOptionsValue: "SAMEORIGIN" #CSP takes care of this but may be needed for organizr.
          contentTypeNosniff: true
          browserXssFilter: true
          sslForceHost: true # add sslHost to all of the services
          sslHost: "next.{{ net_domain.tld }}"
          referrerPolicy: "no-referrer"
          featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
          customResponseHeaders:
            X-Robots-Tag: "noindex, nofollow"
            server: ""
      nextcloud-redirect:
        redirectRegex:
          regex: "https://(.*)/.well-known/(?:card|cal)dav"
          replacement: "https://${1}/remote.php/dav"

  uptime:
    - group: services
      type: port
    - group: databases
      name: "postgres_nextcloud"
      type: postgres
      databaseConnectionString: "postgres://{{ common_user }}:{{ postgres_pass }}@{{ net_hosts[net_svc.postgres.host] }}:{{ net_svc.postgres.port }}/nextcloud"
