obsidian:
  container:
    image: ghcr.io/sytone/obsidian-remote:0.1.1
    ports:
      - "{{ net_svc.obsidian.port }}:8080"
    volumes:
      - "{{ common_dir }}/obsidian/vaults:/vaults"
      - "{{ common_dir }}/obsidian/config:/config"
    env:
      DOCKER_MODS: "linuxserver/mods:universal-git"
      # CUSTOM_USER: "sysadm"
      # PASSWORD: "test"

  traefik:

  uptime:
    group: services
