syncthing:
  image: lscr.io/linuxserver/syncthing:1.27.6
  hostname: "syncthing"
  ports:
    - "{{ net_svc.syncthing.port }}:8384"
    - 22000:22000/tcp
    - 22000:22000/udp
    - 21027:21027/udp
  volumes:
    - "{{ common_dir }}/syncthing/config:/config"
    - "{{ common_data_dir }}/syncthing:/data"

  traefik:

  uptime:
    group: services
    type: port
    port: "{{ net_svc.syncthing.port }}"
    hostname: "{{ net_hosts[net_svc.syncthing.host] }}"
