---

- name: Install k3s
  ansible.builtin.include_role:
    name: xanmanning.k3s
    public: true
  vars:
    k3s_state: installed

- name: Copy kubeconfig project directory
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ common_k8s_root }}/kubeconfig"
    flat: true
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: Update kubeconfig with the correct IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ common_k8s_root }}/kubeconfig"
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ k3s_registration_address }}:6443"

- name: Resource Readiness Check
  run_once: true
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ item.namespace | default('') }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 360
  loop:
    - kind: Deployment
      name: tigera-operator
      namespace: tigera-operator
    - kind: Installation
      name: default
    - kind: ApplicationSet
      name: manifest-apps
  register: _resource_check
  when:
    - k3s_server_manifests_templates | length > 0
        or k3s_server_manifests_urls | length > 0
    - k3s_control_node is defined
    - k3s_control_node

# NOTE
# Cleaning up the manifests from the /var/lib/rancher/k3s/server/manifests directory
# is needed because k3s has an awesome "feature" to always re-deploy them when the k3s
# service is restarted. Removing them does not uninstall the manifests from your cluster.

- name: Remove deployed manifest templates
  ansible.builtin.file:
    path: "{{ k3s_server_manifests_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    state: absent
  loop: "{{ k3s_server_manifests_templates | default([]) }}"

- name: Remove deployed manifest urls
  ansible.builtin.file:
    path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
    state: absent
  loop: "{{ k3s_server_manifests_urls | default([]) }}"
