---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/k8s"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  ANSIBLE_PLAYBOOK_DIR: "playbooks"

includes:
  precommit: .taskfiles/precommit.yml
  ansible:
    taskfile: .taskfiles/ansible.yml
    aliases: [a]
    dir: ansible
  app:
    taskfile: .taskfiles/app.yml
    dir: ansible
  tf: .taskfiles/terraform.yml

tasks:
  default:
    desc: List tasks
    cmds:
      - go-task --list-all

  init:
    desc: Initialize workstation dependencies
    cmds:
      - yay -S {{.DEPS}}
      - direnv allow {{.ROOT_DIR}}
      - task: precommit:init
      - task: ansible:pip
      - task: ansible:galaxy
    preconditions:
      - sh: command -v yay
        msg: |
          yay is not installed
    vars:
      DEPS: >-
        age
        direnv
        go-yq
        helm
        jq
        kubectl
        kustomize
        git-crypt
        python-pre-commit
        sops
        terraform
        terragrunt
        tflint
        yamllint
        argocd
        doppler-cli-bin
        k9s
