---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/k8s"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/tf"

includes:
  precommit: .taskfiles/precommit.yml
  ansible: .taskfiles/ansible.yml
  tf: .taskfiles/terraform.yml

tasks:
  default:
    desc: List tasks
    cmds:
      - go-task --list-all

  init:
    desc: Initialize workstation dependencies
    cmds:
      - yay -S {{.DEPS}}
      - direnv allow {{.ROOT_DIR}}
      - task: precommit:init
      - task: ansible:galaxy
    preconditions:
      - sh: command -v yay
        msg: |
          yay is not installed
    vars:
      DEPS: >-
        age
        ansible
        ansible-core
        ansible-lint
        direnv
        go-yq
        helm
        jq
        kubectl
        kustomize
        molecule
        git-crypt
        molecule-docker
        python-pre-commit
        sops
        terraform
        tflint
        yamllint
        argocd
        doppler-cli-bin
        k9s
