---
- block:
    - name: Check existing ACME accounts
      ansible.builtin.command: pvenode acme account list
      register: _acme_account_list
      changed_when: false

    - name: Register ACME account
      ansible.builtin.expect:
        command: pvenode acme account register {{ pve_acme.account }} {{ pve_acme.email }} --directory {{ pve_acme.url }}
        responses:
          (.*)Do you agree to the above terms(.*): "y"
      register: _acme_account_result
      failed_when: "'Registration successful' not in _acme_account_result.stdout"
      when: pve_acme.account not in _acme_account_list.stdout

    - name: Check existing plugins
      ansible.builtin.command: pvenode acme plugin list
      register: _acme_plugin_list
      changed_when: false

    - block:
        - name: Create temporary env file
          ansible.builtin.copy:
            content: "{{ _cf_env }}"
            dest: /tmp/cf.env
          vars:
            _cf_env: |
              CF_Account_ID={{ pve_acme.cf_account_id }}
              CF_Email={{ pve_acme.cf_email }}
              CF_Key={{ pve_acme.cf_key }}
              CF_Token={{ pve_acme.cf_token }}
              CF_Zone_ID={{ pve_acme.cf_zone_id }}

        - name: Add cloudflare plugin
          ansible.builtin.command: pvenode acme plugin add dns {{ pve_acme.plugin }} --api cf --data /tmp/cf.env
      always:
        - name: Delete temporary env file
          ansible.builtin.file:
            path: /tmp/cf.env
            state: absent
      when: pve_acme.plugin not in _acme_plugin_list.stdout

    - name: Set ACME config
      ansible.builtin.shell: |
        pvenode config set --acme account={{ pve_acme.account }}
        pvenode config set --acmedomain0 {{ ansible_hostname }}.{{ net_domain.tld_local }},plugin={{ pve_acme.plugin }}

    - name: Order certificate
      ansible.builtin.command: pvenode acme cert order --force=1
