---
- name: Set facts
  ansible.builtin.set_fact:
    pve:
      image: "{{ pve_vm.image | default(pve_default_img) }}"
      template: "{{ pve_img_dir }}/{{ pve_default_img | basename }}"
      user: "{{ pve_vm.user | default(common_user) }}"
      group: "{{ pve_vm.user | default(common_group) }}"
      user_id: "{{ pve_vm.user_id | default(common_user_id) }}"
      group_id: "{{ pve_vm.group_id | default(common_group_id) }}"
      password: "{{ pve_vm.password | default(common_pass) }}"
      storage: "{{ pve_vm.storage | default('local-lvm') }}"

- block:
    - name: Provision image
      block:
        - name: Ensure image and template directories exist
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ pve_img_dir }}"
            - "{{ pve_template_dir }}"

        - name: Download cloud-init image
          ansible.builtin.get_url:
            url: "{{ _pve.image }}"
            dest: "{{ pve_img_dir }}/{{ _pve.image | basename }}"

        - name: Create template image
          ansible.builtin.copy:
            src: "{{ pve_img_dir }}/{{ _pve.image | basename }}"
            dest: "{{ _pve.template }}"
            remote_src: yes

        - name: Download public SSH keys
          ansible.builtin.get_url:
            url: "{{ _pve_vm.ssh_keys | default(pve_authorized_keys) }}"
            dest: /tmp/authorized_keys

        - name: Create sudoers file
          ansible.builtin.copy:
            content: "{{ _pve.user }} ALL=(ALL) NOPASSWD: ALL"
            dest: /tmp/sudoers

        - name: Customize template
          ansible.builtin.command: "{{ item }}"
          loop:
            - virt-customize -a {{ _pve.template }} --update
            - virt-customize -a {{ _pve.template }} --install qemu-guest-agent
            - virt-customize -a {{ _pve.template }} --run-command "useradd -m --shell /bin/bash {{ _pve.user }} --uid {{ _pve.user_id }}"
            - virt-customize -a {{ _pve.template }} --password {{ _pve.user }}:password:{{ _pve.password }}
            - virt-customize -a {{ _pve.template }} --run-command 'mkdir -p /home/{{ _pve.user }}/.ssh'
            - virt-customize -a {{ _pve.template }} --ssh-inject {{ _pve.user }}:file:/tmp/authorized_keys
            - virt-customize -a {{ _pve.template }} --run-command 'chown -R {{ _pve.user }}:{{ _pve.group }} /home/{{ _pve.user }}'
            - virt-customize -a {{ _pve.template }} --upload /tmp/sudoers:/etc/sudoers.d/{{ _pve.user }}
            - virt-customize -a {{ _pve.template }} --run-command 'chmod 0440 /etc/sudoers.d/{{ _pve.user }}'
            - virt-customize -a {{ _pve.template }} --run-command 'chown root:root /etc/sudoers.d/{{ _pve.user }}'
            - virt-customize -a {{ _pve.template }} --run-command '>/etc/machine-id'
          register: _result
          failed_when: _result.stderr != '' and 'already exists' not in _result.stderr

        - name: Provision VM
          ansible.builtin.command: "{{ item }}"
          loop:
            - qm create {{ _pve_vm.vmid }} --name {{ _pve_vm.hostname }}
            - qm importdisk {{ _pve_vm.vmid }} {{ _pve.template }} {{ _pve.storage }}
            - qm set {{ _pve_vm.vmid }} --memory {{ _pve_vm.memory }} --cores {{ _pve_vm.cores }}
            - qm set {{ _pve_vm.vmid }} --net0 virtio,bridge=vmbr0,tag={{ _pve_vm.network.tag | default(20) }},macaddr={{ _pve_vm.network.hwaddr }} --ipconfig0 ip=dhcp
            - qm set {{ _pve_vm.vmid }} --scsihw virtio-scsi-pci --scsi0 {{ _pve.storage }}:vm-{{ _pve_vm.vmid }}-disk-0
            - qm set {{ _pve_vm.vmid }} --boot c --bootdisk scsi0
            - qm set {{ _pve_vm.vmid }} --ide2 {{ _pve.storage }}:cloudinit
            - qm set {{ _pve_vm.vmid }} --serial0 socket --vga serial0
            - qm set {{ _pve_vm.vmid }} --agent enabled=1
          register: _result
          failed_when: _result.stderr != ''

        - name: Migrate VM
          ansible.builtin.command: qm migrate {{ _pve_vm.vmid }} {{ _pve_vm.node }}
          register: _result
          failed_when: _result.stderr != ''
  delegate_to: "{{ pve_vm.provision_node | default(groups['pve'][0]) }}"
  vars:
    _pve: "{{ pve }}"
    _pve_vm: "{{ pve_vm }}"

- name: Resize VM
  ansible.builtin.command: qm resize {{ _pve_vm.vmid }} scsi0 {{ _pve_vm.size }}G
  register: _result
  failed_when: _result.stderr != ''
  delegate_to: "{{ _pve_vm.node }}"
  vars:
    _pve_vm: "{{ pve_vm }}"
