apiVersion: ENC[AES256_GCM,data:uUY=,iv:5fisU2BBtkXgW4yOhh7gk3It+uKbp/oXVVE+Dbyi8OI=,tag:RQsiknqJZyjleWpJJOTgRA==,type:str]
data:
    doppler-token: ENC[AES256_GCM,data:EbS0RoU1sq+9MMGWu9Q5u5mHoHyVmgiYjNRAa1Q7yKSwowOznAk3y+KLUXxkWLOCVCDGZTiTjkvlvxdq+/aP0ORmXWROiXxh,iv:OqC/GsFdSBSDsoPLUhazmA4svZlmoPfcPb3ULqa/Zwg=,tag:ckXK9HVIpIUA5dILh2kl5Q==,type:str]
kind: ENC[AES256_GCM,data:ySR4Jtet,iv:FBD3jmBngZrkPJw227/SP78wcG383rdb2kPbQBFDySg=,tag:Ge2BS7kOcohEEr7ATwxsMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sZT3VXG+1niwYRvSqQ==,iv:BQ6S286F1cVSdjnIlbB/HovMEuPIxj0awf59gZhmyB0=,tag:CKxltnQeb4N/C5HVMoNpng==,type:str]
    namespace: ENC[AES256_GCM,data:3I5UqQSTWLwVRZA=,iv:yuKezqODEF4UWGL7xepu0LIh7qd2c0vdUmip+iUCFj8=,tag:sDGBvjOkwLrSFCp/9qb95Q==,type:str]
type: ENC[AES256_GCM,data:ZkNWMYrN,iv:LXvrDT64iTIvkk371XeGu+siP8GIlSCQF418zaPd2iA=,tag:uKNNsym0Yav6xXarf9BI2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cel4a0p36k2rq8wr5n6x7ewc2hw76m2d60wkvl20jpu5zm7lcnsqvexwc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZlVwNFYvMGRjSEd2cHZi
            KzFnUVlIbDBMRCtCaHlTa0l3cXRCSHVZQWhRCjd2SURXS1pxWHlyTWZVM0g5Zkp4
            L1NIYXhpcDhHQjJ0ZUZJbmJ3M0NuMlUKLS0tIFBqMzVOQnFkeHVUUTZKVGVxVzBx
            cTJCM0FYZUJhdTJFeSt4cDdwYUk0UDAKo4DS6fSX9ZfB+u/X9NayIrilsHHOnEIQ
            GmztxZx+er04elvWmmgpTfuWv8Z5g+JSARgNgbZQz4l6loZDb35/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T04:50:31Z"
    mac: ENC[AES256_GCM,data:OkQzeR/AfmrNsz9tcwf0lNMUhxluWM/ISLUyPl0RWtA9+Rkhby9SeVOvIYrFFjsZ9Ij4IOnT6aVwTK98XxWI9tg9VJmrXx84jKgKpYAaOueIjXKixFuy6nvTT170YbMTzQj31lYIFuhBINFNReSYvsXBR0pHaFNWECZ6CQ1F+2s=,iv:OEK5C8I7ZVApb+NNJP2mnnzadrGL8tPh9Ms9q+mn4LU=,tag:SZap/IYuZhC15Qyf7qEbNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
