---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app syncthing
  namespace: &namespace network
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cilium-gateway
      namespace: kube-system
  components:
    - ../../../components/common/external
  path: ./k8s/apps/network/external-svc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      EXTERNAL_IP: 100.94.245.44
      EXTERNAL_PORT: "8384"
      EXTERNAL_DOMAIN: sync.sbbh.cloud

