---
- name: Apply CRD manifests to the cluster
  ansible.builtin.shell: kubectl apply --server-side --force-conflicts -f "{{ item }}"
  loop: "{{ k8s.crds }}"

- name: Apply Kustomize CRD manifests
  ansible.builtin.shell: kubectl apply --server-side --force-conflicts -k "{{ item }}"
  loop: "{{ k8s.crds_kustomize }}"
