---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-downloader
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        initContainers:
          init:
            image: &image
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: v0.2.0@sha256:99e8d42199dd69cfb36498e4ca99c13c93ab513980ee33c1b9837aa1ab163fb9
            command:
              - bash
              - -c
              - "exec cp -r /usr/local/lib/python3.10/site-packages/seleniumbase/drivers/* /mnt"
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

        containers:
          app:
            image: *image
            env:
              FLASK_PORT: &port 80
              FLASK_DEBUG: false
              AA_BASE_URL: https://annas-archive.li
              INGEST_DIR: &ingest /cwa-book-ingest
              BOOK_LANGUAGE: en
            command: [python, -m, app] # don't run annoying init script
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /request/api/status
                    port: *port
              readiness: *probe
              startup: *probe
            securityContext: *securityContext
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits: # some of the cloudflare attempts can really spike usage
                cpu: 1
                memory: 1Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [65534] # nobody group, required since calibre-web-automated tries to use root on startup
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.sbbh.cloud"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]

    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              # chromium needs the XDG_CONFIG_HOME created
              # because user 1000 doesn't exist, ~ = /
              - path: /.config
                subPath: config
              - path: /tmp
                subPath: tmp
              - path: /var/log/cwa-book-downloader/
                subPath: log
              - path: /app/downloaded_files
                subPath: download
              - path: /usr/local/lib/python3.10/site-packages/seleniumbase/drivers
                subPath: drivers
            init:
              - path: /mnt
                subPath: drivers
      media:
        type: nfs
        server: nas-k8s.int.sbbh.cloud
        path: /data/nvme
        advancedMounts:
          *app :
            app:
              - path: *ingest
                subPath: downloads/openbooks
