apiVersion: ENC[AES256_GCM,data:Jls=,iv:IpEAW2/lZFWKd2tLprhOzxrEqjgHtJABaq10s1foJAo=,tag:dd8FkoTHhcpIZWobWGwa5w==,type:str]
data:
    admin.password: ENC[AES256_GCM,data:c4BpBrN/Okfujh9WRKt2cLUt/gT4v+zlxKK9PdIA+ly7UI228Mxe8qLKjr49ILUIlGdYBQWlTGmc9V+WmByUMj4EDjL6cdtqEirTCyvLwr4=,iv:eJprkMjaD91MN6A3ovqLx5sq370ZLU9lSpSVYDvrGo4=,tag:s0m3uyvqX926zpDMpDneCA==,type:str]
kind: ENC[AES256_GCM,data:GVHhE6pf,iv:vYhjFmA9RpNqz10O2TABURsujmsxE064qs+uUBIhjtw=,tag:q0C/q3/AkbGVfKYNigM4Mw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p+04HqwSCbK9eYW81Q==,iv:piMIWs+oBV19SyeK9v8+QImKiCmx2TfG2GJejSmh1+8=,tag:vwfIXmlBTRoM9eg84Ir4mw==,type:str]
    namespace: ENC[AES256_GCM,data:u72HFbV/,iv:XghqYIwkNc0qr3tefOgWMkro3duHfJZoLZgEy9RrA2c=,tag:5NIZi+JIb0KLVfrruE8JpQ==,type:str]
    annotations:
        kustomize.config.k8s.io/behavior: ENC[AES256_GCM,data:cwNw89A=,iv:+K0qDWEjw/+ClpEqjZ0On8wlTMHMbvQKMX3FLyhACpk=,tag:7KqNIh+PnQ+V3QkfN51nbg==,type:str]
type: ENC[AES256_GCM,data:w5JKuNeG,iv:cTi71K6EbK6OOkfFkmEk2/k0BjoKK/Uteo5DoAIlBSA=,tag:JSf1970HlHtypwy9NZVb0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cel4a0p36k2rq8wr5n6x7ewc2hw76m2d60wkvl20jpu5zm7lcnsqvexwc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c0xrQ3lXUVcwazIwTlJt
            OWhKTTYvQW1sYUk1TXhZSWN4SUFyeEpYdlFFCnJ4NWFQSjJSeit1eGhmTURQQ2hw
            ZDlaSEw3U0t4YnVMZjJHdVFOd0R2ZG8KLS0tIEl3NUpWTy9UQjlhQ1JBSk5HMm9O
            OVNNVjdXR0svZWlsZm1zeVdIVGRqMFEKcUfaN7CI74eqqCkIWSH+n+8NEIVy5mP+
            1ID5tlVDwXvN5ahBBiz4yLsS3T5ITw9QCFFBmFa62insTCy/RSM+IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-19T12:50:35Z"
    mac: ENC[AES256_GCM,data:0lXlVYijcHOGJ3Hf3v07fWoPUmEKmnuwqHlpjNKchEg9aUGl+LJWk5yh7gFed//yMnxn2UeJbNDoJmObu+FBDJqFTY7ISWD6YE7MF99kKHYr8CQNtEsVUwws1gxanJ5vFY1JmoPEsac6ZqPneuGZLPQ5WQsyazmVKPg0njJOYwM=,iv:CjOyL3i9BxmRyTwtq0+Lt6H5VXOkhCPnPFUL7m6po0s=,tag:1/q0nlUMg65GFsvVfKam5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
