apiVersion: ENC[AES256_GCM,data:uoI=,iv:7q5Eb6yTz/1OxfDXs5Ir2aR+9OYzp6LObwhDEpHgR9s=,tag:v8l3s6eD+J67JemDKhTkOQ==,type:str]
data:
    password: ENC[AES256_GCM,data:MaOykok0AORSfxAfHcQ2pK93ABChczZZuwCXQHqsATaWIX2srKPMkqQUUhBDI00eHkuolR3cWlQ=,iv:6UN/MvgCdmjm8XpF5BWKObpeg9Ug7/wTc1zd1j78paY=,tag:QU+H+IWb5QFv9XcZQmkp5g==,type:str]
    project: ENC[AES256_GCM,data:D+kT1+k0aw3z0CTc,iv:DOcOdtWSlxSzuOzLN5KaQl3UrHbDSD5T7IzLXK6K38w=,tag:zXF/ETPo4CvFxaDd7+F4kg==,type:str]
    type: ENC[AES256_GCM,data:MO7rFQ==,iv:QXWF0PctsnsjAhwyqw5pqYSGezcQ+0gw7fHFZs0Cg9E=,tag:Ap3CUrwexhVc/JmjNu7/vA==,type:str]
    url: ENC[AES256_GCM,data:u7a8ana97XVrRLhsdkvEdQIQCLZsQ6ub/6/FNA4vroC1CJAQHe8oysiH+wUo2LED,iv:M0hbQdH50A6KnAnhzhp7V81oraaimH6cT4ophrBDy6M=,tag:KFE1zocs+G5JjGiZpcmldQ==,type:str]
    username: ENC[AES256_GCM,data:EfiLZax/rpQ=,iv:EtdPvkjTZre4i0gvUmiYSB9yqMTXVQ+tV4UyLa56Sd0=,tag:N6NBHYkW6jy6NZvcAfvXhg==,type:str]
kind: ENC[AES256_GCM,data:ZVmLdqlf,iv:Icil01XdxK5r0LyQs57/stWjKoAR9enGb6prN1O2isM=,tag:yPC47CQvqyfdJLB4ed3vYw==,type:str]
metadata:
    annotations:
        managed-by: ENC[AES256_GCM,data:gmbxI/Q410aWS6GbybqI28ey,iv:lxEBDQMq5/tMXL17XhyinGvfFhrTFYkjJ1AYCha95dI=,tag:PQPjbQi3tSYqxEl79fQ/6w==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:+DQ93aaooJxk3A==,iv:WCgt9SI2elEuZV5kBXVGiwCvI5LTScxlkvSrypwntJg=,tag:S+tzDb7eRtZymIpz7//+4g==,type:str]
    name: ENC[AES256_GCM,data:GMc70lN5Hc8JqMc1,iv:X4hw9uiYOOCDgjGZdZRtjVCJBMapBsBUzVLvM+1qWq8=,tag:Ll9jRiLdHEVw/1h5hJnhrQ==,type:str]
    namespace: ENC[AES256_GCM,data:BEq+qmhg,iv:2prcD0VkACqIGDS/gLtEoQBRWH02kLAvgNmzeJJ2RsI=,tag:7Mpz1xYOJM6LqUjcabZ57g==,type:str]
type: ENC[AES256_GCM,data:b6dFvmAD,iv:D919ttkKSUNOju6+OW7sbfemK9Tgfz1l+REPMYRYLdw=,tag:QwJoHYaaP8rsBaP1WSUP0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cel4a0p36k2rq8wr5n6x7ewc2hw76m2d60wkvl20jpu5zm7lcnsqvexwc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxalpjalZuN3dNNk5EOXU3
            RytIS05saFdnMU4xaFZzdDg4UnJiSlprLzBzCm9lZDFvcWNnL3Q5RXJqSUQvU2Ew
            U1pneHhHRUVPNnphbm8xNGZCMGg0eEUKLS0tIG1kVklnRFFFU3VUQ29SODhTZzRB
            blZqWUhWZ0o3YTZPN1JqU1AvRUc3OFkKJxn3tmFRjI3cY1UpqgrU+c1Exa/iSJqL
            MHQJG53b8vw0rWWL0ec3P5IU+tBQFlGjQ+adJ0dvXlgc3EuVOBQvzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T03:53:24Z"
    mac: ENC[AES256_GCM,data:dN1ZW6sRIMXr94T5cLqnSBPRAlerApDWlqqP82Jk5lNrZ3q2UxHLzJxoP6IvQlbaTlZaHAK6QeiuixhIwycJzrkM+ORqmh4sn/k+KW5p+Cb3pVHo63zAfKqHcusmixH1sxMOkOmk9/ig5GQ6Mbnm3+fUuOl3TiHl1MYuxw1nf5E=,iv:RHHIL0Qwgn1sI8M0XlH2up9iXe8U/wSwdjAzd77eQZU=,tag:beG7sXPeuiTe6PJnDq6rqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
