---
container:
  networks:
    - name: mesh
  security_opts:
    - "no-new-privileges:true"
  restart: true
  recreate: true
  restart_policy: unless-stopped
  state: started
  log_driver: json-file
  log_options:
    max-size: 10m
    max-file: "3"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  env:
    PUID: "{{ common_user_id | string }}"
    PGID: "{{ common_group_id | string }}"
    TZ: "{{ common_timezone }}"
  comparisons:
    volumes: strict
    networks: strict
    env: strict
    labels: strict

db:
  default: postgres
  postgres:
    host: "{{ network_svc.postgres.host }}"
    user: "{{ common_user }}"
    pass: "{{ postgres_pass }}"

uptime:
  interval: 60
  maxretries: 1
  notification_names:
    - "discord"

networks:
  mesh:
    driver: bridge
    ipam_config:
      - subnet: "192.168.100.0/24"
