---
audiobookshelf:
  container:
    image: ghcr.io/advplyr/audiobookshelf:2.8.1
    ports:
      - "{{ net_svc.audiobookshelf.port }}:80"
    volumes:
      - "{{ common_apps_dir }}/audiobookshelf/config:/config"
      - "{{ common_apps_dir }}/audiobookshelf/metadata:/metadata"
      - "/data/media-fast/books/audiobooks:/data"

  traefik:
    name: audiobooks
    rtr_middlewares:
      - crowdsec
      - rate-limit
      - compress

  uptime:
    group: media
