---
authentik_server:
  name: authentik-server
  container:
    image: ghcr.io/goauthentik/server:2023.8.2
    command: server
    ports:
      - "{{ network_svc.authentik_server.port }}:9000"
    volumes:
      - "{{ common_dir }}/authentik/media:/media"
      - "{{ common_dir }}/authentik/custom-templates:/templates"
      - "{{ common_dir }}/authentik/geoip/data:/geoip"
    env:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__PASSWORD: "{{ redis_pass }}"
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: "{{ common_user }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ postgres_pass }}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_SECRET_KEY: "{{ authentik_key }}"
      AUTHENTIK_COOKIE_DOMAIN: "{{ network_domain.tld }}"

  traefik:
    routers:
      - name: "auth"
        rule: "Host(`auth.{{ network_domain.tld }}`)"
        middlewares:
          - chain-external-no-auth
        service: auth-svc
      - name: "auth-outpost"
        rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.{{ network_domain.tld }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
        middlewares:
          - chain-external-no-auth
        service: auth-outpost-svc
    services: |
      auth-svc:
        loadBalancer:
          servers:
            - url: "http://{{ network_svc.authentik_server.host }}:{{ network_svc.authentik_server.port }}"
      auth-outpost-svc:
        loadBalancer:
          servers:
            - url: "http://{{ network_svc.authentik_server.host }}:{{ network_svc.authentik_server.port }}/outpost.goauthentik.io"

  uptime:
    - group: system
    - group: databases
      name: "postgres_authentik"
      type: postgres
      databaseConnectionString: "postgres://{{ common_user }}:{{ postgres_pass }}@{{ network_hosts[network_svc.postgres.host] }}:{{ network_svc.postgres.port }}/authentik"

authentik_worker:
  name: authentik-worker
  container:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2023.8.2
    command: worker
    volumes:
      - "{{ common_dir }}/authentik/media:/media"
      - "{{ common_dir }}/authentik/custom-templates:/templates"
      - "{{ common_dir }}/authentik/geoip/data:/geoip"
    env:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__PASSWORD: "{{ redis_pass }}"
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: "{{ common_user }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ postgres_pass }}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_SECRET_KEY: "{{ authentik_key }}"
      AUTHENTIK_COOKIE_DOMAIN: "{{ network_domain.tld }}"
