---
authentik:
  name: authentik
  container:
    image: ghcr.io/goauthentik/server:2023.10.5
    restart_policy: always
    command: server
    ports:
      - "{{ net_svc.authentik.port }}:9000"
    volumes:
      - "{{ common_apps_dir }}/authentik/media:/media"
      - "{{ common_apps_dir }}/authentik/custom-templates:/templates"
      - "{{ common_apps_dir }}/geoip/data:/geoip"
    env:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__PASSWORD: "{{ vault_redis_pass }}"
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: "{{ common_user }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ vault_postgres_pass }}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_SECRET_KEY: "{{ vault_authentik_key }}"
      AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ vault_authentik_pass }}"
      AUTHENTIK_BOOTSTRAP_EMAIL: "auth@{{ net_domain.tld }}"
      AUTHENTIK_COOKIE_DOMAIN: "{{ net_domain.tld }}"

  dependents:
    - authentik_worker

  db:
    - type: postgres
      name: authentik

  traefik:
    routers:
      - name: "auth"
        rule: "Host(`auth.{{ net_domain.tld }}`)"
        middlewares:
          - chain-external-no-auth
        service: auth-svc
      - name: "auth-outpost"
        rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.{{ net_domain.tld }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
        middlewares:
          - chain-external-no-auth
        service: auth-outpost-svc
    services: |
      auth-svc:
        loadBalancer:
          servers:
            - url: "http://authentik:{{ net_svc.authentik.port }}"
      auth-outpost-svc:
        loadBalancer:
          servers:
            - url: "http://authentik:{{ net_svc.authentik.port }}/outpost.goauthentik.io"

  uptime:
    - group: system
    - group: databases
      type: postgres
      dbname: authentik

authentik_worker:
  name: authentik-worker
  container:
    image: ghcr.io/goauthentik/server:2023.10.5
    restart_policy: always
    command: worker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ common_apps_dir }}/authentik/media:/media"
      - "{{ common_apps_dir }}/authentik/certs:/certs"
      - "{{ common_apps_dir }}/authentik/custom-templates:/templates"
      - "{{ common_apps_dir }}/geoip/data:/geoip"
    env:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__PASSWORD: "{{ vault_redis_pass }}"
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: "{{ common_user }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ vault_postgres_pass }}"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_SECRET_KEY: "{{ vault_authentik_key }}"
      AUTHENTIK_COOKIE_DOMAIN: "{{ net_domain.tld }}"
