---
bazarr:
  container:
    image: lscr.io/linuxserver/bazarr:1.2.4
    ports:
      - "{{ network_svc.bazarr.port }}:6767"
    volumes:
      - "{{ common_dir }}/bazarr/config:/config"
      - "{{ common_media_dir }}:/data"

  traefik:
    routers:
      - name: "bazarr"
        rule: "Host(`bazarr.{{ network_domain.tld }}`)"
      - name: "bazarr-bypass"
        rule: "Host(`bazarr.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_bazarr_api }}`)"
        middlewares:
          - chain-no-auth

  uptime:
    group: media
