---
bazarr:
  container:
    image: lscr.io/linuxserver/bazarr:1.2.4
    ports:
      - "{{ net_svc.bazarr.port }}:6767"
    volumes:
      - "{{ common_apps_dir }}/bazarr/config:/config"
      - "/data/media/movies:/data/movies"
      - "/data/media/tv:/data/tv"

  traefik:
    routers:
      - name: "bazarr"
        rule: "Host(`bazarr.{{ net_domain.tld }}`)"
      - name: "bazarr-bypass"
        rule: "Host(`bazarr.{{ net_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_bazarr_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
