---
calibre:
  container:
    image: lscr.io/linuxserver/calibre:7.8.0
    ports:
      - "{{ net_svc.calibre.port }}:8080"
      - "{{ net_svc.calibre.port_server }}:8081"
    volumes:
      - "{{ common_apps_dir }}/calibre:/config"
      - "/data/media-fast/books/ebooks:/books"
      - "/data/downloads:/downloads"

  traefik:
    routers:
      - name: "calibre"
        rule: "Host(`calibre.{{ net_domain.tld }}`)"
        service: calibre-svc
      - name: "calibre-server"
        rule: "Host(`calibre-server.{{ net_domain.tld }}`)"
        service: calibre-server-svc
    services: |
      calibre-svc:
        loadBalancer:
          servers:
            - url: "http://{{ net_svc.calibre.host }}:{{ net_svc.calibre.port }}"
      calibre-server-svc:
        loadBalancer:
          servers:
            - url: "http://{{ net_svc.calibre.host }}:{{ net_svc.calibre.port_server }}"

  uptime:
    group: media

calibre_web:
  name: calibre-web
  container:
    image: lscr.io/linuxserver/calibre-web:0.6.21
    env:
      DOCKER_MODS: linuxserver/mods:universal-calibre
    ports:
      - "{{ net_svc.calibre_web.port }}:8083"
    volumes:
      - "{{ common_apps_dir }}/calibre-web:/config"
      - "/data/media-fast/books/ebooks:/books"

  traefik:
    name: books
    rtr_middlewares:
      - chain-external-no-auth

  uptime:
    group: media
