---

defaults:
  networks:
    - name: mesh
  security_opts:
    - "no-new-privileges:true"
  restart: true
  recreate: true
  restart_policy: unless-stopped
  state: started
  log_driver: json-file
  log_options:
    max-size: 10m
    max-file: "3"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    PUID: "{{ common_user_id | string }}"
    PGID: "{{ common_group_id | string }}"
    TZ: "{{ common_timezone }}"

networks:
  mesh:
    driver: bridge
    ipam_config:
      - subnet: "192.168.100.0/24"
