---
freshrss:
  container:
    image: freshrss/freshrss:1.23.0
    ports:
      - "{{ net_svc.freshrss.port }}:80"
    volumes:
      - "{{ common_apps_dir }}/freshrss/data:/var/www/FreshRSS/data"
      - "{{ common_apps_dir }}/freshrss/extensions:/var/www/FreshRSS/extensions"
    env:
      TRUSTED_PROXY: "{{ net_hosts.bastion.ip }}/32"
      DB_HOST: postgres
      DB_BASE: freshrss
      DB_USER: "{{ common_user }}"
      DB_PASSWORD: "{{ vault_postgres_pass }}"
      CRON_MIN: "*/20"
      FRESHRSS_INSTALL: >
        --api_enabled
        --base_url https://freshrss.{{ net_domain.tld }}
        --db-base freshrss
        --db-host postgres
        --db-password {{ vault_postgres_pass }}
        --db-type pgsql
        --db-user {{ common_user }}
        --default_user {{ common_user }}
        --language en
      FRESHRSS_USER: >
        --api_password {{ vault_freshrss_api }}
        --email freshrss@{{ net_domain.tld }}
        --language en
        --password {{ vault_freshrss_pass }}
        --user {{ common_user }}

  traefik:

  db:
    - type: postgres
      name: freshrss

  uptime:
    - group: services
    - group: databases
      type: postgres
      dbname: freshrss
