---
gluetun:
  container:
    image: qmcgaw/gluetun:pr-1543
    capabilities:
      - net_admin
    ports:
      - "{{ network_svc.gluetun.port }}:8000"
      - "{{ network_svc.qbittorrent.port }}:8080"
    volumes:
      - "{{ common_dir }}/gluetun:/gluetun"
    env:
      VPN_SERVICE_PROVIDER: "protonvpn"
      VPN_PORT_FORWARDING: "on"
      OPENVPN_USER: "{{ network_vpn.openvpn_user}}+pmp"
      OPENVPN_PASSWORD: "{{ network_vpn.openvpn_pass }}"
      SERVER_COUNTRIES: "Singapore"
      FIREWALL_OUTBOUND_SUBNETS: "{{ network_cidr.lan }}"
      HEALTH_TARGET_ADDRESS: "cloudflare.com:443"
      HEALTH_VPN_DURATION_INITIAL: "10s"
      HEALTH_VPN_DURATION_ADDITION: "30s"
      HEALTH_SUCCESS_WAIT_DURATION: "60s"

  dependents:
    - qbittorrent

  uptime:
    - name: gluetun_dns
      type: keyword
      url: "http://{{ network_hosts[network_svc.gluetun.host] }}:{{ network_svc.gluetun.port }}/v1/dns/status"
      keyword: running
      group: gluetun
    - name: gluetun_vpn
      type: keyword
      url: "http://{{ network_hosts[network_svc.gluetun.host] }}:{{ network_svc.gluetun.port }}/v1/openvpn/status"
      keyword: running
      group: gluetun
    - name: gluetun_ip
      type: keyword
      url: "http://{{ network_hosts[network_svc.gluetun.host] }}:{{ network_svc.gluetun.port }}/v1/publicip/ip"
      upsideDown: yes
      keyword: "{{ lookup('ansible.builtin.url', 'http://ifconfig.me', http_agent='curl/8.2.1') }}"
      group: gluetun
    - name: gluetun_port
      type: keyword
      url: "http://{{ network_hosts[network_svc.gluetun.host] }}:{{ network_svc.gluetun.port }}/v1/openvpn/portforwarded"
      upsideDown: yes
      keyword: ":0"
      group: gluetun
