homer:
  image: b4bz/homer:v23.05.1
  ports:
    - "{{ network_svc.homer.port }}:8080"
  volumes:
    - "{{ common_dir }}/homer/assets:/www/assets"

  traefik:
    name: home
    rtr_middlewares:
      - local-only

  homer:
    - category: various
      name: Homer
      icon: "fas fa-home"
      subtitle: Dashboard
      tag: app
      url: https://hom.sbbh.cloud
