linkace:
  container:
    image: linkace/linkace:v1.14.2-simple
    ports:
      - "{{ net_svc.linkace.port }}:80"
    volumes:
      - "{{ common_apps_dir }}/linkace/backups:/app/storage/app/backups"
      - "{{ common_apps_dir }}/linkace/.env:/app/.env"
      - "{{ common_apps_dir }}/logs/linkace:/app/storage/logs"
    env:
      APP_KEY: "{{ vault_linkace_key }}"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "linkace"
      SETUP_COMPLETED: "true"
      DB_USERNAME: "{{ common_user }}"
      DB_PASSWORD: "{{ vault_postgres_pass }}"

      MAIL_FROM_ADDRESS: "{{ common_email_svc }}"
      MAIL_FROM_NAME: "linkace"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "{{ common_email_server }}"
      MAIL_PORT: "{{ common_email_port | string }}"
      MAIL_USERNAME: "{{ common_email_user }}"
      MAIL_PASSWORD: "{{ common_email_pass }}"
      MAIL_ENCRYPTION: "{{ common_email_protocol }}"

  traefik:
    name: bookmarks

  files:
    - dest: "{{ common_apps_dir }}/linkace"
    - src: .env.j2
      dest: "{{ common_apps_dir }}/linkace/.env"

  uptime:
    - group: services
    - group: databases
      type: postgres
      dbname: linkace
