---

linx:
  image: andreimarcu/linx-server:v2.3.8
  command: |
    -config /data/linx-server.conf \
    -siteurl "https://linx.{{ network_domain_tld }}/" \
    -cleanup-every-minutes 5 \
    -realip = true

  ports:
    - "{{ network_svc.linx.port }}:8080"
  volumes:
    - "{{ common_dir }}/linx/linx-server.conf:/data/linx-server.conf"
    - "{{ common_data_dir }}/temp/meta:/data/meta"
    - "{{ common_data_dir }}/temp/files:/data/files"

  traefik:
