---

minio:
  image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
  ports:
    - "{{ network_svc.minio.port }}:9000"
    - "{{ network_svc.minio.port_console }}:9090"
  environment:
    MINIO_ROOT_USER: "{{ common_user }}"
    MINIO_ROOT_PASSWORD: "{{ minio_pass }}"
    MINIO_SITE_REGION: "ap-southeast-4"
    MINIO_SERVER_URL: "https://s3.{{ network_domain.tld }}"
  volumes:
    - "{{ common_backup_dir | default('') }}/minio:/data"
  command: server /data --console-address ":9090"

  traefik:
    routers:
    - name: "s3"
      rule: "Host(`s3.{{ network_domain.tld }}`)"
      middlewares:
        - local-only
      service: s3-svc
    - name: "minio"
      rule: "Host(`minio.{{ network_domain.tld }}`)"
      middlewares:
        - chain-auth
      service: minio-svc
    services: |
      s3-svc:
        loadBalancer:
          servers:
            - url: "http://{{ network_svc.minio.host }}:{{ network_svc.minio.port }}"
      minio-svc:
        loadBalancer:
          servers:
            - url: "http://{{ network_svc.minio.host }}:{{ network_svc.minio.port_console }}"
