---
minio:
  container:
    image: quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z
    ports:
      - "{{ net_svc.minio.port }}:9000"
      - "{{ net_svc.minio.port_console }}:9001"
    env:
      MINIO_ROOT_USER: "{{ common_user }}"
      MINIO_ROOT_PASSWORD: "{{ vault_minio_pass }}"
      MINIO_SITE_REGION: "ap-southeast-4"
      MINIO_SERVER_URL: "https://s3.{{ net_domain.tld }}"
    volumes:
      - "{{ common_apps_dir }}/minio:/data"
    command: server /data --console-address ":9001"

  traefik:
    routers:
      - name: "s3"
        rule: "Host(`s3.{{ net_domain.tld }}`)"
        service: s3-svc
      - name: "minio"
        rule: "Host(`minio.{{ net_domain.tld }}`)"
        service: minio-svc
    services: |
      s3-svc:
        loadBalancer:
          servers:
            - url: "http://{{ net_svc.minio.host }}:{{ net_svc.minio.port }}"
      minio-svc:
        loadBalancer:
          servers:
            - url: "http://{{ net_svc.minio.host }}:{{ net_svc.minio.port_console }}"

  uptime:
    url: "http://{{ net_svc.minio.host }}:{{ net_svc.minio.port_console }}"
    group: system
