---
openspeedtest:
  container:
    image: openspeedtest/latest:v2.0.2
    ports:
      - "{{ network_svc.openspeedtest.port }}:3000"

  traefik:
    name: speedtest
    rtr_middlewares:
      - chain-auth
      - buffer-limit
    middlewares: |
      buffer-limit:
        buffering:
          maxRequestBodyBytes: 10000000000

  uptime:
    group: services
