---
overseerr:
  container:
    image: lscr.io/linuxserver/overseerr:1.33.2
    ports:
      - "{{ net_svc.overseerr.port }}:5055"
    volumes:
      - "{{ common_apps_dir }}/overseerr/config:/config"

  traefik:
    name: requests
    rtr_middlewares:
      - chain-external-no-auth

  uptime:
    group: media
