---

overseerr:
  image: lscr.io/linuxserver/overseerr:1.33.1
  ports:
    - "{{ network_svc.overseerr.port }}:5055"
  volumes:
    - "{{ common_dir }}/overseerr/config:/config"

  traefik:
    name: requests
    rtr_middlewares:
      - chain-no-auth
