---
pbk:
  traefik:
    services: |
      pbk-svc:
        loadBalancer:
          serversTransport: "pbk"
          servers:
            - url: "https://{{ network_hosts.pbk }}:{{ network_svc.pbk.port }}"
    serversTransports: |
      pbk:
        insecureSkipVerify: true

  uptime:
    - name: pbk-webui
      group: pve
      url: "https://{{ network_hosts.pbk }}:{{ network_svc.pbk.port }}"
      ignoreTls: yes
    - group: servers
      type: ping
      hostname: "{{ network_hosts.pbk }}"
