---

pihole:
  traefik:
    routers:
    - name: "pihole"
      rule: "Host(`pihole.{{ network_domain.tld }}`)"
      middlewares:
        - chain-auth
        - pihole-strip-admin
        - pihole-add-admin
    - name: "pihole-bypass"
      rule: "Host(`pihole.{{ network_domain.tld }}`) && Query(`auth={{ network_svc.dns.api }}`)"
      middlewares:
        - chain-no-auth
    middlewares: |
      pihole-strip-admin:
        stripPrefix:
          prefixes:
            - "/admin"
      pihole-add-admin:
        addPrefix:
          prefix: "/admin"
