---
pikvm:
  traefik:
    name: kvm
    services: |
      pikvm-svc:
        loadBalancer:
          serversTransport: "pikvm"
          servers:
            - url: "https://{{ network_hosts.pikvm }}"
    serversTransports: |
      pikvm:
        insecureSkipVerify: true

  uptime:
    - name: pikvm-webui
      group: system
      ignoreTls: yes
    - group: servers
      type: ping
      hostname: "{{ network_hosts.pikvm }}"
