---

pikvm:
  traefik:
    name: kvm
    services: |
      pikvm-svc:
        loadBalancer:
          serversTransport: "pikvm"
          servers:
            - url: "https://{{ network_svc.pikvm.ip }}"
    serversTransports: |
      pikvm:
        insecureSkipVerify: true
