---
plex:
  traefik:
    rtr_middlewares:
      - chain-external-no-auth

  uptime:
    - name: plex-webui
      group: media
      ignoreTls: yes
    - group: servers
      type: ping
      hostname: "{{ net_hosts.plex.ip }}"

plex_meta_manager:
  name: plex-meta-manager
  container:
    image: meisnate12/plex-meta-manager:v1.19.1
    volumes:
      - "{{ common_apps_dir }}/plex-meta-manager/config:/config"

  files:
    - dest: "{{ common_apps_dir }}/plex-meta-manager/config/assets"
    - src: config.yml.j2
      dest: "{{ common_apps_dir }}/plex-meta-manager/config/config.yml"
      mode: "0660"
    - src: config.yml.j2
      dest: "{{ common_apps_dir }}/plex-meta-manager/config/config_manual.yml"
      mode: "0660"
    - src: refresh_movies.yml
      dest: "{{ common_apps_dir }}/plex-meta-manager/config/refresh_movies.yml"
    - src: refresh_tv.yml
      dest: "{{ common_apps_dir }}/plex-meta-manager/config/refresh_tv.yml"
    - src: run.sh.j2
      dest: "{{ common_apps_dir }}/plex-meta-manager/run.sh"
      mode: "0700"
