---
plex:
  traefik:
    rtr_middlewares:
      - chain-external-no-auth

  uptime:
    - name: plex-webui
      group: media
      ignoreTls: yes
    - group: servers
      type: ping
      hostname: "{{ network_hosts.plex }}"
