---

portainer:
  image: portainer/portainer-ce:2.18.1
  command: "-H unix:///var/run/docker.sock"
  ports:
    - "{{ network_svc.portainer.port }}:9000"
    - "{{ network_svc.portainer.agent_port }}:8000"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "{{ common_dir }}/portainer/data:/data"

  traefik:
