---

portainer:
  image: portainer/portainer-ce:2.18.3
  command: "-H unix:///var/run/docker.sock"
  ports:
    - "{{ network_svc.portainer.port }}:9000"
    - "{{ network_svc.portainer.agent_port }}:8000"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "{{ common_dir }}/portainer/data:/data"

  traefik:

portainer_agent_bastion:
  name: portainer-agent
  image: portainer/agent:2.18.4
  ports:
    - "{{ network_svc.portainer.agent_port }}:9001"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/var/lib/docker/volumes:/var/lib/docker/volumes"

portainer_agent_nas:
  name: portainer-agent
  image: portainer/agent:2.18.4
  ports:
    - "{{ network_svc.portainer.agent_port }}:9001"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/volume1/@docker/volumes:/volume1/@docker/volumes"
