---

portainer_agent_nas:
  name: portainer-agent
  image: portainer/agent:2.18.1
  ports:
    - "{{ network_svc.nas_srv.ip }}:{{ network_svc.portainer.agent_port }}:9001"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/volume1/@docker/volumes:/volume1/@docker/volumes"
