---

portainer_agent_bastion:
  name: portainer-agent
  image: portainer/agent:2.18.1
  ports:
    - "{{ network_svc.portainer.agent_port }}:9001"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/var/lib/docker/volumes:/var/lib/docker/volumes"
