---
prowlarr:
  container:
    image: lscr.io/linuxserver/prowlarr:1.7.4
    ports:
      - "{{ network_svc.prowlarr.port }}:9696"
    volumes:
      - "{{ hostvars[network_svc.prowlarr.host]['common_dir'] }}/prowlarr/config:/config"

  traefik:
    routers:
      - name: "prowlarr"
        rule: "Host(`prowlarr.{{ network_domain.tld }}`)"
      - name: "prowlarr-bypass"
        rule: "Host(`prowlarr.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_prowlarr_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
