---
prowlarr:
  image: lscr.io/linuxserver/prowlarr:version-1.6.3.3608
  ports:
    - "{{ network_svc.prowlarr.port }}:9696"
  volumes:
    - "{{ common_dir }}/prowlarr/config:/config"

  traefik:
    routers:
      - name: "prowlarr"
        rule: "Host(`prowlarr.{{ network_domain.tld }}`)"
      - name: "prowlarr-bypass"
        rule: "Host(`prowlarr.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_prowlarr_api }}`)"
        middlewares:
          - chain-no-auth

  uptime:
    group: media
