---
prowlarr:
  container:
    image: lscr.io/linuxserver/prowlarr:1.11.4
    ports:
      - "{{ net_svc.prowlarr.port }}:9696"
    volumes:
      - "{{ common_apps_dir }}/prowlarr/config:/config"

  traefik:
    routers:
      - name: "prowlarr"
        rule: "Host(`prowlarr.{{ net_domain.tld }}`)"
      - name: "prowlarr-bypass"
        rule: "Host(`prowlarr.{{ net_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_prowlarr_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
