---

pve:
  traefik:
    rtr_middlewares:
      - local-only

    services: |
      pve-svc:
        failover:
          healthCheck: {}
          service: pve-main-svc
          fallback: pve-backup-svc

      pve-main-svc:
        loadBalancer:
          healthCheck:
            path: /
            interval: 10s
            timeout: 3s
          servers:
            - url: "https://{{ network_svc.pve.host[0] }}.{{ network_domain.tld_local }}:{{ network_svc.pve.port }}"

      pve-backup-svc:
        loadBalancer:
          healthCheck:
            path: /
            interval: 10s
            timeout: 3s
          servers:
            - url: "https://{{ network_svc.pve.host[1] }}.{{ network_domain.tld_local }}:{{ network_svc.pve.port }}"
