---

qbittorrent:
  image: lscr.io/linuxserver/qbittorrent:4.5.2-r2-ls259
  network_mode: "container:gluetun"
  networks:
  volumes:
    - "{{ common_dir }}/qbittorrent/config:/config"
    - "{{ common_dir }}/qbittorrent/mam_id:/mam_id"
    - "{{ common_media_dir }}/downloads/torrents:/downloads"
  command: bash -c "curl -c /config/mam.cookies -b mam_id=$(</mam_id) https://t.myanonamouse.net/json/dynamicSeedbox.php ; sleep infinity"

  traefik:
    rtr_middlewares:
      - chain-no-auth
