---
radarr:
  container:
    image: lscr.io/linuxserver/radarr:4.7.5
    ports:
      - "{{ network_svc.radarr.port }}:7878"
    volumes:
      - "{{ common_dir }}/radarr/config:/config"
      - "{{ common_dir }}/radarr/MediaCover:/config/MediaCover"
      - "{{ common_media_dir }}:/data"

  traefik:
    routers:
      - name: "radarr"
        rule: "Host(`radarr.{{ network_domain.tld }}`)"
      - name: "radarr-bypass"
        rule: "Host(`radarr.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_radarr_api }}`)"
        middlewares:
          - chain-no-auth

  uptime:
    group: media
