---
radarr:
  container:
    image: lscr.io/linuxserver/radarr:5.4.6
    ports:
      - "{{ net_svc.radarr.port }}:7878"
    volumes:
      - "{{ common_apps_dir }}/radarr/config:/config"
      - "{{ common_apps_dir }}/radarr/MediaCover:/config/MediaCover"
      - "/data:/data"

  traefik:
    routers:
      - name: "radarr"
        rule: "Host(`radarr.{{ net_domain.tld }}`)"
      - name: "radarr-bypass"
        rule: "Host(`radarr.{{ net_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_radarr_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
