---
readarr_ebooks:
  name: readarr-ebooks
  container:
    image: lscr.io/linuxserver/readarr:0.3.3-develop
    ports:
      - "{{ network_svc.readarr_ebooks.port }}:8787"
    volumes:
      - "{{ common_dir }}/readarr_ebooks/config:/config"
      - "{{ common_media_dir }}:/data"

  traefik:
    routers:
      - name: "readarr-eb"
        rule: "Host(`readarr-eb.{{ network_domain.tld }}`)"
      - name: "readarr-eb-bypass"
        rule: "Host(`readarr-eb.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_readarr_ebooks_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media

readarr_audiobooks:
  name: readarr-audiobooks
  container:
    image: lscr.io/linuxserver/readarr:0.3.3-develop
    ports:
      - "{{ network_svc.readarr_audiobooks.port }}:8787"
    volumes:
      - "{{ common_dir }}/readarr_audiobooks/config:/config"
      - "{{ common_media_dir }}:/data"

  traefik:
    routers:
      - name: "readarr-ab"
        rule: "Host(`readarr-ab.{{ network_domain.tld }}`)"
      - name: "readarr-ab-bypass"
        rule: "Host(`readarr-ab.{{ network_domain.tld }}`) && Headers(`X-API-KEY`, `{{ media_readarr_audiobooks_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
