---
readarr:
  name: readarr
  container:
    image: lscr.io/linuxserver/readarr:0.3.11-develop
    ports:
      - "{{ net_svc.readarr.port }}:8787"
    volumes:
      - "{{ common_apps_dir }}/readarr/config:/config"
      - "/data:/data"

  traefik:
    routers:
      - name: "readarr"
        rule: "Host(`readarr.{{ net_domain.tld }}`)"
      - name: "readarr-bypass"
        rule: "Host(`readarr.{{ net_domain.tld }}`) && Headers(`X-API-KEY`, `{{ vault_readarr_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
