---
sabnzbd:
  container:
    image: lscr.io/linuxserver/sabnzbd:4.0.3
    ports:
      - "{{ net_svc.sabnzbd.port }}:8080"
    volumes:
      - "{{ common_apps_dir }}/sabnzbd/config:/config"
      - "/data/downloads/nzb:/data"

  traefik:
    routers:
      - name: "sabnzbd"
        rule: "Host(`sabnzbd.{{ net_domain.tld }}`)"
      - name: "sabnzbd-bypass"
        rule: "Host(`sabnzbd.{{ net_domain.tld }}`) && Query(`apikey={{ media_sabnzbd_api }}`)"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
