---

sabnzbd:
  image: lscr.io/linuxserver/sabnzbd:4.0.2
  ports:
    - "{{ network_svc.sabnzbd.port }}:8080"
  volumes:
    - "{{ common_dir }}/sabnzbd/config:/config"
    - "{{ common_media_dir }}:/data"

  traefik:
    routers:
    - name: "sabnzbd"
      rule: "Host(`sabnzbd.{{ network_domain.tld }}`)"
    - name: "sabnzbd-bypass"
      rule: "Host(`sabnzbd.{{ network_domain.tld }}`) && Query(`apikey={{ media_sabnzbd_api }}`)"
      middlewares:
        - chain-no-auth
