---
tautulli:
  container:
    image: ghcr.io/tautulli/tautulli:v2.13.2
    ports:
      - "{{ net_svc.tautulli.port }}:8181"
    volumes:
      - "{{ common_apps_dir }}/tautulli/config:/config"

  traefik:
    routers:
      - name: "tautulli"
        rule: "Host(`tautulli.{{ net_domain.tld }}`)"
      - name: "tautulli-pub"
        rule: "Host(`tautulli.{{ net_domain.tld }}`) && (PathPrefix(`/image/`) || PathPrefix(`/newsletter/`))"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
