---
threadfin:
  container:
    image: fyb3roptik/threadfin:1.1.14
    ports:
      - "{{ net_svc.threadfin.port }}:34400"
      - "{{ net_svc.threadfin.port_dvr }}:1900"
    volumes:
      - "{{ common_apps_dir }}/threadfin/conf:/home/threadfin/conf"
      - "/dev/shm:/tmp/threadfin"

  traefik:
