---

traefik_cs_bouncer:
  name: traefik-cs-bouncer
  image: fbonalair/traefik-crowdsec-bouncer:0.5.0
  restart_policy: always
  environment:
    CROWDSEC_BOUNCER_API_KEY: "{{ crowdsec_bouncer_api_key | default(omit) }}"
    CROWDSEC_AGENT_HOST: "crowdsec:8080"
    GIN_MODE: release
    CROWDSEC_BOUNCER_LOG_LEVEL: "2"
