---
unpackerr:
  container:
    image: golift/unpackerr:0.13.0
    volumes:
      - "{{ common_apps_dir }}/unpackerr/config:/config"
      - "/data:/data"
    env:
      UN_SONARR_0_URL: "http://sonarr:{{ net_svc.sonarr.port }}"
      UN_SONARR_0_API_KEY: "{{ media_sonarr_api }}"
      UN_RADARR_0_URL: "http://radarr:{{ net_svc.radarr.port }}"
      UN_RADARR_0_API_KEY: "{{ media_radarr_api }}"
