---
uptimekuma:
  container:
    image: louislam/uptime-kuma:1.23.13
    ports:
      - "{{ net_svc.uptimekuma.port }}:3001"
    volumes:
      - "{{ common_apps_dir }}/uptimekuma:/app/data"

  traefik:
    routers:
      - name: "uptime"
        rule: "Host(`uptime.{{ net_domain.tld }}`)"
      - name: "uptime-bypass"
        rule: "Host(`uptime.{{ net_domain.tld }}`) && Headers(`Authorization`, `Basic {{ (':' ~ vault_uptime_kuma_api) | b64encode }}`)"
        middlewares:
          - chain-external-no-auth
      - name: "status"
        rule: "Host(`status.{{ net_domain.tld }}`)"
        middlewares:
          - chain-external-no-auth
          - uptimekuma-status
    middlewares: |
      uptimekuma-status:
        replacePathRegex:
          regex: "^/$"
          replacement: "/status/homelab"
