---
uptimekuma:
  image: louislam/uptime-kuma:1.22.1
  ports:
    - "{{ network_svc.uptimekuma.port }}:3001"
  volumes:
    - "{{ common_dir }}/uptimekuma:/app/data"

  traefik:
    routers:
      - name: "uptime"
        rule: "Host(`uptime.{{ network_domain.tld }}`)"
      - name: "uptime-bypass"
        rule: "Host(`uptime.{{ network_domain.tld }}`) && Headers(`Authorization`, `Basic {{ (':' ~ uptime_kuma_api) | b64encode }}`)"
        middlewares:
          - chain-no-auth
      - name: "status"
        rule: "Host(`status.{{ network_domain.tld }}`)"
        middlewares:
          - chain-no-auth
          - uptimekuma-status
    middlewares: |
      uptimekuma-status:
        replacePathRegex:
          regex: "^/$"
          replacement: "/status/homelab"
