---
wizarr:
  container:
    image: ghcr.io/wizarrrr/wizarr:2.2.0
    ports:
      - "{{ network_svc.wizarr.port }}:5690"
    volumes:
      - "{{ common_dir }}/wizarr/config:/data/database"
    env:
      APP_URL: "https://invites.{{ network_domain.tld }}"
      DISABLE_BUILTIN_AUTH: "true"

  traefik:
    routers:
      - name: "wizarr"
        rule: "Host(`invites.{{ network_domain.tld }}`)"
      - name: "wizarr-bypass"
        rule: "Host(`invites.{{ network_domain.tld }}`) && (Path(`/join`, `/setup`) || PathPrefix(`/j/`, `/setup/`, `/static/`))"
        middlewares:
          - chain-no-auth

  uptime:
    group: media
