---
wizarr:
  container:
    image: ghcr.io/wizarrrr/wizarr:4.1.0
    ports:
      - "{{ net_svc.wizarr.port }}:5690"
    volumes:
      - "{{ common_apps_dir }}/wizarr/config:/data/database"
    env:
      APP_URL: "https://invites.{{ net_domain.tld }}"
      DISABLE_BUILTIN_AUTH: "True"

  traefik:
    routers:
      - name: "wizarr"
        rule: "Host(`invites.{{ net_domain.tld }}`)"
      - name: "wizarr-bypass"
        rule: "Host(`invites.{{ net_domain.tld }}`) && (Path(`/join`, `/setup`) || PathPrefix(`/j/`, `/setup/`, `/static/`))"
        middlewares:
          - chain-external-no-auth

  uptime:
    group: media
    type: port
    port: "{{ net_svc.wizarr.port }}"
    hostname: "{{ net_hosts[net_svc.wizarr.host].ip }}"
