---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pve-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: prompve/prometheus-pve-exporter
              tag: 3.5.5
            ports:
              - name: http
                containerPort: 9221
                protocol: TCP
            args:
              - --config.file
              - /etc/prometheus-pve-exporter/pve.yml
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9221
                  initialDelaySeconds: 30
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9221
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 128Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 9221
    persistence:
      config:
        type: secret
        name: prometheus-pve-exporter-secret
        globalMounts:
          - path: /etc/prometheus-pve-exporter
            readOnly: true

