apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.6.0
    valuesFile: values.yaml
    namespace: longhorn-system
    releaseName: longhorn
    includeCRDs: true

resources:
  - externalsecret.yaml
  - ingressroute.yaml
  - recurringjob-snapshots.yaml
  - recurringjob-backups.yaml
