---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app storage-ready
  namespace: &namespace flux-system
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./k8s/apps/flux-system/healthcheck/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  healthChecks:
    - apiVersion: &cephApiVersion ceph.rook.io/v1
      kind: &cephKind CephCluster
      name: rook-ceph
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: volsync
      namespace: volsync-system
    - &crd
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: replicationsources.volsync.backube
    - <<: *crd
      name: replicationdestinations.volsync.backube
    - <<: *crd
      name: externalsecrets.external-secrets.io
  healthCheckExprs:
    - apiVersion: *cephApiVersion
      kind: *cephKind
      failed: status.ceph.health == 'HEALTH_ERR'
      current: status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
