---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.sbbh.cloud/sysadm/homelab.git
    targetRevision: main
    path: k8s/drone
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
