---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kube-runner
  namespace: drone
  labels:
    app.kubernetes.io/name: drone-kube-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-kube-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-kube-runner
    spec:
      containers:
      - name: drone-kube-runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: drone.k8s.sbbh.cloud
        - name: DRONE_RPC_PROTO
          value: https
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-doppler-secret
              key: DRONE_RPC_SECRET
        - name: DRONE_SECRET_PLUGIN_ENDPOINT
          value: http://drone-secrets.drone.svc.cluster.local:3000
        - name: DRONE_SECRET_PLUGIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: drone-doppler-secret
              key: DRONE_RPC_SECRET
