resources:
  - namespace.yaml
  # - server-deployment.yaml
  # - kube-runner-deployment.yaml
  # - kube-runner-rbac.yaml
  # - kube-secrets-deployment.yaml
  - cache-pvc.yaml
  - ingress.yaml

# namespace: drone
