apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-fluentd
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-fluentd

  dataFrom:
    - extract:
        key: FLUENTD_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
