apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: cf-token

  dataFrom:
    - extract:
        key: CLOUDFLARE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
