---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: v1.13.2
    valuesFile: values.yaml
    namespace: cert-manager
    includeCRDs: true

  - name: trust-manager
    repo: https://charts.jetstack.io
    releaseName: trust-manager
    version: v0.7.1
    namespace: cert-manager
    includeCRDs: true

resources:
  - namespace.yaml
  - externalsecret.yaml
  - clusterissuer-selfsigned.yaml
  - clusterissuer-selfsigned-ca.yaml
  - clusterissuer-stg.yaml
  - clusterissuer-prd.yaml
  - certificate-selfsigned.yaml
