apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: eck-operator
    repo: https://helm.elastic.co
    version: 2.8.0
    namespace: monitoring
    releaseName: es
    includeCRDs: true

resources:
  - namespace.yaml
  - externalsecret.yaml
  - secrets/admin-externalsecret.yaml
  - secrets/fluentd-externalsecret.yaml
  - secrets/prometheus-externalsecret.yaml
  - secrets/fluentd-role.yaml
  - secrets/prometheus-role.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - ingressroute.yaml
