apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: postgres-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_USERNAME }}"
        password: "{{ .POSTGRES_PASSWORD }}"
        postgres-password: "{{ .POSTGRES_ADMIN_PASSWORD }}"

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
