apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-drone
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-drone

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-postgres
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-postgres

  dataFrom:
    - extract:
        key: POSTGRES_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-db-secret
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-db-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_USERNAME }}"
        password: "{{ .POSTGRES_PASSWORD }}"

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-renovate
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-renovate

  dataFrom:
    - extract:
        key: DRONE_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
    - extract:
        key: DOCKER_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
    - extract:
        key: GITHUB_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
