apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops

helmCharts:
  - name: drone
    repo: https://charts.drone.io
    version: 0.6.4
    valuesFile: values-drone.yaml
    namespace: gitops
    releaseName: drone
    includeCRDs: true

  - name: drone-runner-docker
    repo: https://charts.drone.io
    version: 0.6.1
    valuesFile: values-runner.yaml
    namespace: gitops
    releaseName: drone-runner-docker
    includeCRDs: true

  - name: drone-kubernetes-secrets
    repo: https://charts.drone.io
    version: 0.1.4
    valuesFile: values-kubernetes-secrets.yaml
    namespace: gitops
    releaseName: drone-kubernetes-secrets
    includeCRDs: true

resources:
  - externalsecret.yaml
  - cluster.yaml
  - ingressroute.yaml
  - pvc-cache.yaml
