---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflare-tunnel
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cloudflare-tunnel-secret
      namespace: *namespace
  interval: 1h
  path: ./k8s/apps/network/cloudflare-tunnel/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cloudflare-tunnel-secret
        optional: true
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false

