apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-longhorn
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-longhorn

  dataFrom:
    - find:
        path: LONGHORN_
