---

ghost:
  host: hl-services
  image: ghost:5.46.1
  restart_policy: always
  ports:
    - "{{ network_svc.ghost.port }}:2368"
  volumes:
    - "{{ common_dir }}/ghost/content:/var/lib/ghost/content"
  environment:
    url: "https://{{ network_domain.tld }}"
    database__client: mysql
    database__connection__host: mysql
    database__connection__user: root
    database__connection__password: "{{ mysql_pass }}"
    database__connection__database: ghost
