---

netbootxyz:
  host: hl-services
  image: netbootxyz/netbootxyz:0.6.7-nbxyz18
  ports:
    - "{{ network_svc.netbootxyz.port }}:3000"
    - "69:69/udp"
  volumes:
    - "{{ common_dir }}/netbootxyz/config:/config"
    - "{{ common_data_dir }}/netboot:/assets"
