---

postgres:
  host: hl-services
  image: postgres:12-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
    start_period: 20s
    interval: 30s
    retries: 5
    timeout: 5s
  ports:
    - "{{ network_svc.postgres.port }}:5432"
  volumes:
    - "{{ common_dir }}/postgresql/data:/var/lib/postgresql/data"
  environment:
    POSTGRES_USER: "{{ common_user }}"
    POSTGRES_PASSWORD: "{{ postgres_pass }}"
