---

qbittorrent:
  host: nas
  image: lscr.io/linuxserver/qbittorrent:4.5.2-r2-ls259
  network_mode: "container:gluetun"
  networks: 
  volumes:
    - "{{ common_dir }}/qbittorrent/config:/config"
    - "{{ common_media_dir }}/downloads/torrents:/downloads"
  command: bash -c "curl -c /config/mam.cookies -b 'mam_id={{ media_mam_id }}' https://t.myanonamouse.net/json/dynamicSeedbox.php ; sleep infinity"
