---

whoami:
  host: bastion
  image: traefik/whoami
  labels:
    traefik.enable: "true"
    traefik.http.routers.whoami-rtr.rule: "Host(`whoami.{{ network_domain.tld }}`)"
    traefik.http.routers.whoami-rtr.entrypoints: "websecure"
    traefik.http.routers.whoami-rtr.middlewares: "chain-auth@file"
