---

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ common_dir }}/traefik/configs"
    - "{{ common_dir }}/logs/traefik"

- name: Create empty ACME certificate
  ansible.builtin.file:
    path: "{{ common_dir }}/traefik/acme.json"
    state: touch
    mode: 0600
    modification_time: preserve
    access_time: preserve

- name: Import copy task for dynamic configs
  ansible.builtin.import_tasks: copy_config.yml

- name: Copy logrotate file
  ansible.builtin.template:
    src: "logrotate.j2"
    dest: "/etc/logrotate.d/traefik"
    mode: 0644

- name: Ensure pip modules are installed
  ansible.builtin.pip:
    name: passlib

- name: Create htpasswd file
  community.general.htpasswd:
    path: "{{ common_dir }}/traefik/.htpasswd"
    name: sysadm
    password: "{{ common_pass }}"
    mode: 0640

- name: Create traefik container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: traefik

- name: Create whoami container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: whoami

- name: Restart Traefik logging
  ansible.builtin.command: docker kill --signal="USR1" traefik
  changed_when: false
