---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Infra
        HOMEPAGE_VAR_PVE_TOKEN: "{{ .pve_user }}!{{ .pve_token }}"
        HOMEPAGE_VAR_PVE_SECRET: "{{ .pve_token_value }}"
        HOMEPAGE_VAR_OPNSENSE_KEY: "{{ .opnsense_key }}"
        HOMEPAGE_VAR_OPNSENSE_SECRET: "{{ .opnsense_secret }}"
        HOMEPAGE_VAR_UNIFI_PASS: "{{ .unifi_pass }}"
        # Media
        HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: "{{ .audiobookshelf_token }}"
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .bazarr_token }}"
        HOMEPAGE_VAR_CALIBRE_USER: "{{ .calibre_user }}"
        HOMEPAGE_VAR_CALIBRE_PASS: "{{ .calibre_pass }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_token }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .prowlarr_token }}"
        HOMEPAGE_VAR_QB_USER: "{{ .qb_user }}"
        HOMEPAGE_VAR_QB_PASS: "{{ .qb_pass }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_token }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .sabnzbd_token }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_token }}"
  data:
    # Infra
    - secretKey: pve_user
      remoteRef:
        key: ops/infra/pve-monitoring
        property: user
    - secretKey: pve_token
      remoteRef:
        key: ops/infra/pve-monitoring
        property: token
    - secretKey: pve_token_value
      remoteRef:
        key: ops/infra/pve-monitoring
        property: token_value
    - secretKey: opnsense_key
      remoteRef:
        key: ops/infra/opnsense
        property: key
    - secretKey: opnsense_secret
      remoteRef:
        key: ops/infra/opnsense
        property: secret
    - secretKey: unifi_pass
      remoteRef:
        key: ops/infra/unifi
        property: password
    # Media
    - secretKey: audiobookshelf_token
      remoteRef:
        key: ops/media/audiobookshelf
        property: api_key
    - secretKey: bazarr_token
      remoteRef:
        key: ops/media/bazarr
        property: api_key
    - secretKey: calibre_user
      remoteRef:
        key: ops/media/calibre
        property: user
    - secretKey: calibre_pass
      remoteRef:
        key: ops/media/calibre
        property: password
    - secretKey: plex_token
      remoteRef:
        key: ops/media/plex
        property: token
    - secretKey: prowlarr_token
      remoteRef:
        key: ops/media/prowlarr
        property: api_key
    - secretKey: qb_user
      remoteRef:
        key: ops/media/qbittorrent
        property: user
    - secretKey: qb_pass
      remoteRef:
        key: ops/media/qbittorrent
        property: password
    - secretKey: radarr_token
      remoteRef:
        key: ops/media/radarr
        property: api_key
    - secretKey: sabnzbd_token
      remoteRef:
        key: ops/media/sabnzbd
        property: api_key
    - secretKey: sonarr_token
      remoteRef:
        key: ops/media/sonarr
        property: api_key
