apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-prometheus
  namespace: logging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: es-prometheus
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .promUser }}"
        password: "{{ .promPassword }}"
        roles: prometheus_role

  dataFrom:
    - extract:
        key: EFK_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
