---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-sbbh-cloud
  namespace: traefik
spec:
  secretName: k8s-sbbh-cloud-tls
  issuerRef:
    name: letsencrypt-stg
    # name: letsencrypt-prd
    kind: ClusterIssuer
  commonName: "*.k8s.sbbh.cloud"
  dnsNames:
    - "k8s.sbbh.cloud"
    - "*.k8s.sbbh.cloud"
