globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

additionalVolumeMounts:
  - name: logs
    mountPath: /var/log/traefik

logs:
  general:
    level: DEBUG
  access:
    enabled: true
    format: json
    bufferingSize: 1000
    filePath: "/var/log/traefik/access.log"
    fields:
      headers:
        defaultmode: keep

deployment:
  replicas: 2
  additionalContainers:
    - name: tail-accesslogs
      image: busybox
      args: ["/bin/sh", "-c", "tail -n+1 -F /var/log/traefik/access.log"]
      volumeMounts:
        - name: logs
          mountPath: /var/log/traefik
  additionalVolumes:
    - name: logs

ports:
  web:
    redirectTo: websecure
    # redirectTo:
    #   port: websecure
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.11.5.2/32"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.11.5.2/32"
  websecure:
    tls:
      enabled: true
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.11.5.2/32"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.11.5.2/32"

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    ingressClass: traefik-external

# service:
#   annotations:
#     service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
#   spec:
#     loadBalancerIP: 10.11.80.100
#     externalTrafficPolicy: Local
#   env:
#     - name: TZ
#       value: "Australia/Melbourne"

metrics:
  prometheus: {}
  service:
    enabled: true
  serviceMonitor: {}
