---
endpoints:
  - name: "${APP}"
    group: "${GATUS_GROUP:=internal}"
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.sbbh.cloud"
      query-type: A
    conditions:
      - "len([BODY]) == 0"

