---

- name: Create container {{ run_container }}
  community.docker.docker_container:
    # use defaults
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    networks: "{{ container.networks | default(containers['defaults'].networks) }}"
    restart_policy: "{{ container.restart_policy | default(containers['defaults'].restart_policy) }}"
    state: "{{ container.state | default(containers['defaults'].state) }}"
    log_driver: "{{ container.log_driver | default(containers['defaults'].log_driver) }}"
    log_options: "{{ container.log_options | default(containers['defaults'].log_options) }}"
    security_opts: "{{ container.security_opts | default(containers['defaults'].security_opts) }}"
    volumes: "{{ container.volumes | default([]) + containers['defaults'].volumes }}"
    env: "{{ containers['defaults'].environment | ansible.builtin.combine(container.environment | default([]), list_merge='replace') }}"

    # misc
    exposed_ports: "{{ container.exposed_ports | default(omit) }}"
    ports: "{{ container.ports | default(omit) }}"
    hostname: "{{ container.hostname | default(omit) }}"
    shm_size: "{{ container.shm_size | default(omit) }}"
    command: "{{ container.command | default(omit) }}"
    api_version: "{{ container.api_version | default(omit) }}"
    auto_remove: "{{ container.auto_remove | default(omit) }}"
    blkio_weight: "{{ container.blkio_weight | default(omit) }}"
    cacert_path: "{{ container.cacert_path | default(omit) }}"
    capabilities: "{{ container.capabilities | default(omit) }}"
    cert_path: "{{ container.cert_path | default(omit) }}"
    cleanup: "{{ container.cleanup | default(omit) }}"
    cpu_period: "{{ container.cpu_period | default(omit) }}"
    cpu_quota: "{{ container.cpu_quota | default(omit) }}"
    cpuset_cpus: "{{ container.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ container.cpuset_mems | default(omit) }}"
    cpu_shares: "{{ container.cpu_shares | default(omit) }}"
    detach: "{{ container.detach | default(omit) }}"
    devices: "{{ container.devices | default(omit) }}"
    dns_search_domains: "{{ container.dns_search_domains | default(omit) }}"
    dns_servers: "{{ container.dns_servers | default(omit) }}"
    docker_host: "{{ container.docker_host | default(omit) }}"
    domainname: "{{ container.domainname | default(omit) }}"
    entrypoint: "{{ container.entrypoint | default(omit) }}"
    etc_hosts: "{{ container.etc_hosts | default(omit) }}"
    force_kill: "{{ container.force_kill | default(omit) }}"
    groups: "{{ container.groups | default(omit) }}"
    ignore_image: "{{ container.ignore_image | default(omit) }}"
    interactive: "{{ container.interactive | default(omit) }}"
    ipc_mode: "{{ container.ipc_mode | default(omit) }}"
    keep_volumes: "{{ container.keep_volumes | default(omit) }}"
    kernel_memory: "{{ container.kernel_memory | default(omit) }}"
    key_path: "{{ container.key_path | default(omit) }}"
    kill_signal: "{{ container.kill_signal | default(omit) }}"
    labels: "{{ container.labels | default(omit) }}"
    links: "{{ container.links | default(omit) }}"
    mac_address: "{{ container.mac_address | default(omit) }}"
    memory: "{{ container.memory | default(omit) }}"
    memory_reservation: "{{ container.memory_reservation | default(omit) }}"
    memory_swap: "{{ container.memory_swap | default(omit) }}"
    memory_swappiness: "{{ container.memory_swappiness | default(omit) }}"
    network_mode: "{{ container.network_mode | default(omit) }}"
    oom_killer: "{{ container.oom_killer | default(omit) }}"
    oom_score_adj: "{{ container.oom_score_adj | default(omit) }}"
    paused: "{{ container.paused | default(omit) }}"
    pid_mode: "{{ container.pid_mode | default(omit) }}"
    privileged: "{{ container.privileged | default(omit) }}"
    published_ports: "{{ container.published_ports | default(omit) }}"
    pull: "{{ container.pull | default(omit) }}"
    purge_networks: "{{ container.purge_networks | default(omit) }}"
    read_only: "{{ container.read_only | default(omit) }}"
    recreate: "{{ container.recreate | default(omit) }}"
    restart: "{{ container.restart | default(omit) }}"
    restart_retries: "{{ container.restart_retries | default(omit) }}"
    ssl_version: "{{ container.ssl_version | default(omit) }}"
    stop_signal: "{{ container.stop_signal | default(omit) }}"
    stop_timeout: "{{ container.stop_timeout | default(omit) }}"
    sysctls: "{{ container.sysctls | default(omit) }}"
    timeout: "{{ container.timeout | default(omit) }}"
    tls: "{{ container.tls | default(omit) }}"
    tls_hostname: "{{ container.tls_hostname | default(omit) }}"
    tls_verify: "{{ container.tls_verify | default(omit) }}"
    tmpfs: "{{ container.tmpfs | default(omit) }}"
    trust_image_content: "{{ container.trust_image_content | default(omit) }}"
    tty: "{{ container.tty | default(omit) }}"
    ulimits: "{{ container.ulimits | default(omit) }}"
    user: "{{ container.user | default(omit) }}"
    userns_mode: "{{ container.userns_mode | default(omit) }}"
    uts: "{{ container.uts | default(omit) }}"
    volume_driver: "{{ container.volume_driver | default(omit) }}"
    volumes_from: "{{ container.volumes_from | default(omit) }}"
    working_dir: "{{ container.working_dir | default(omit) }}"
  changed_when: false
