---

- name: Ensure docker network is present
  no_log: "{{ false if debug | default(true) }}"
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ apps.networks[item.name].driver }}"
    driver_options: "{{ apps.networks[item.name].driver_options | default(omit) }}"
    ipam_config: "{{ apps.networks[item.name].ipam_config | default(omit) }}"
  with_items: "{{ app.networks | default(apps['defaults'].networks) }}"
  when: (app.networks is defined and app.networks != None) or app.networks is undefined

- name: Create container {{ app.name }}
  no_log: "{{ false if debug | bool else true }}"
  community.docker.docker_container:
    # use defaults
    name: "{{ app.name }}"
    image: "{{ app.image }}"
    networks: "{{ app.networks | default(apps['defaults'].networks) }}"
    restart_policy: "{{ app.restart_policy | default(apps['defaults'].restart_policy) }}"
    state: "{{ app.state | default(apps['defaults'].state) }}"
    log_driver: "{{ app.log_driver | default(apps['defaults'].log_driver) }}"
    log_options: "{{ app.log_options | default(apps['defaults'].log_options) }}"
    security_opts: "{{ app.security_opts | default(apps['defaults'].security_opts) }}"
    volumes: "{{ app.volumes | default([]) + apps['defaults'].volumes }}"
    env: "{{ apps['defaults'].environment | ansible.builtin.combine(app.environment | default([]), list_merge='replace') }}"
    comparisons: "{{ app.comparisons | default(apps['defaults'].comparisons) }}"

    # misc
    exposed_ports: "{{ app.exposed_ports | default(omit) }}"
    ports: "{{ app.ports | default(omit) }}"
    hostname: "{{ app.hostname | default(omit) }}"
    shm_size: "{{ app.shm_size | default(omit) }}"
    command: "{{ app.command | default(omit) }}"
    api_version: "{{ app.api_version | default(omit) }}"
    auto_remove: "{{ app.auto_remove | default(omit) }}"
    blkio_weight: "{{ app.blkio_weight | default(omit) }}"
    cacert_path: "{{ app.cacert_path | default(omit) }}"
    capabilities: "{{ app.capabilities | default(omit) }}"
    cert_path: "{{ app.cert_path | default(omit) }}"
    cleanup: "{{ app.cleanup | default(omit) }}"
    cpu_period: "{{ app.cpu_period | default(omit) }}"
    cpu_quota: "{{ app.cpu_quota | default(omit) }}"
    cpuset_cpus: "{{ app.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ app.cpuset_mems | default(omit) }}"
    cpu_shares: "{{ app.cpu_shares | default(omit) }}"
    detach: "{{ app.detach | default(omit) }}"
    devices: "{{ app.devices | default(omit) }}"
    dns_search_domains: "{{ app.dns_search_domains | default(omit) }}"
    dns_servers: "{{ app.dns_servers | default(omit) }}"
    docker_host: "{{ app.docker_host | default(omit) }}"
    domainname: "{{ app.domainname | default(omit) }}"
    entrypoint: "{{ app.entrypoint | default(omit) }}"
    etc_hosts: "{{ app.etc_hosts | default(omit) }}"
    force_kill: "{{ app.force_kill | default(omit) }}"
    groups: "{{ app.groups | default(omit) }}"
    ignore_image: "{{ app.ignore_image | default(omit) }}"
    interactive: "{{ app.interactive | default(omit) }}"
    ipc_mode: "{{ app.ipc_mode | default(omit) }}"
    keep_volumes: "{{ app.keep_volumes | default(omit) }}"
    kernel_memory: "{{ app.kernel_memory | default(omit) }}"
    key_path: "{{ app.key_path | default(omit) }}"
    kill_signal: "{{ app.kill_signal | default(omit) }}"
    labels: "{{ app.labels | default(omit) }}"
    links: "{{ app.links | default(omit) }}"
    mac_address: "{{ app.mac_address | default(omit) }}"
    memory: "{{ app.memory | default(omit) }}"
    memory_reservation: "{{ app.memory_reservation | default(omit) }}"
    memory_swap: "{{ app.memory_swap | default(omit) }}"
    memory_swappiness: "{{ app.memory_swappiness | default(omit) }}"
    network_mode: "{{ app.network_mode | default(omit) }}"
    oom_killer: "{{ app.oom_killer | default(omit) }}"
    oom_score_adj: "{{ app.oom_score_adj | default(omit) }}"
    paused: "{{ app.paused | default(omit) }}"
    pid_mode: "{{ app.pid_mode | default(omit) }}"
    privileged: "{{ app.privileged | default(omit) }}"
    published_ports: "{{ app.published_ports | default(omit) }}"
    pull: "{{ app.pull | default(omit) }}"
    purge_networks: "{{ app.purge_networks | default(omit) }}"
    read_only: "{{ app.read_only | default(omit) }}"
    recreate: "{{ app.recreate | default(omit) }}"
    restart: "{{ app.restart | default(omit) }}"
    restart_retries: "{{ app.restart_retries | default(omit) }}"
    ssl_version: "{{ app.ssl_version | default(omit) }}"
    stop_signal: "{{ app.stop_signal | default(omit) }}"
    stop_timeout: "{{ app.stop_timeout | default(omit) }}"
    sysctls: "{{ app.sysctls | default(omit) }}"
    timeout: "{{ app.timeout | default(omit) }}"
    tls: "{{ app.tls | default(omit) }}"
    tls_hostname: "{{ app.tls_hostname | default(omit) }}"
    tls_verify: "{{ app.tls_verify | default(omit) }}"
    tmpfs: "{{ app.tmpfs | default(omit) }}"
    tty: "{{ app.tty | default(omit) }}"
    ulimits: "{{ app.ulimits | default(omit) }}"
    user: "{{ app.user | default(omit) }}"
    userns_mode: "{{ app.userns_mode | default(omit) }}"
    uts: "{{ app.uts | default(omit) }}"
    volume_driver: "{{ app.volume_driver | default(omit) }}"
    volumes_from: "{{ app.volumes_from | default(omit) }}"
    working_dir: "{{ app.working_dir | default(omit) }}"
  when: app.image is defined
