---
- name: Create dependent apps
  ansible.builtin.include_role:
    name: apps
  vars:
    _app: "{{ _dependent_item }}"
    _preprocessed: true
  loop: "{{ _app_config.dependents }}"
  loop_control:
    loop_var: _dependent_item
