---
- name: Set traefik facts
  ansible.builtin.set_fact:
    traefik_config: "{{ _app_config.traefik }}"

- name: Create Traefik config for {{ _app }}
  delegate_to: "{{ net_svc.traefik.host }}"
  become: true
  ansible.builtin.template:
    src: traefik-app.yml.j2
    dest: "{{ common_apps_dir }}/traefik/configs/app-{{ _app_name }}.yml"
