---
- name: Set container facts
  no_log: "{{ ci | default(false) }}"
  ansible.builtin.set_fact:
    container: "{{ _defaults.container | ansible.builtin.combine(_app_config.container, list_merge='append_rp', recursive=true) }}"

- name: Set container name fact
  no_log: "{{ ci | default(false) }}"
  ansible.builtin.set_fact:
    container: "{{ container | combine({'name': _app_name}) }}"

- name: Set container host
  ansible.builtin.set_fact:
    container_host: "{{ network_svc[_app].host | mandatory }}"

- name: Ensure Docker network is present on {{ container_host }}
  no_log: "{{ ci | default(false) }}"
  delegate_to: "{{ container_host }}"
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ _defaults.networks[item.name].driver }}"
    driver_options: "{{ _defaults.networks[item.name].driver_options | default(omit) }}"
    ipam_config: "{{ _defaults.networks[item.name].ipam_config | default(omit) }}"
  with_items: "{{ container.networks }}"
  when: container.networks is defined and container.networks != None

- name: Create container {{ container.name }}
  no_log: "{{ ci | default(false) }}"
  delegate_to: "{{ container_host }}"
  community.docker.docker_container:
    name: "{{ container.name | default(omit) }}"
    image: "{{ container.image | default(omit) }}"
    volumes: "{{ container.volumes | default(omit) }}"

    api_version: "{{ container.api_version | default(omit) }}"
    docker_api_version: "{{ container.docker_api_version | default(omit) }}"
    auto_remove: "{{ container.auto_remove | default(omit) }}"
    blkio_weight: "{{ container.blkio_weight | default(omit) }}"
    ca_cert: "{{ container.ca_cert | default(omit) }}"
    tls_ca_cert: "{{ container.tls_ca_cert | default(omit) }}"
    cacert_path: "{{ container.cacert_path | default(omit) }}"
    cap_drop: "{{ container.cap_drop | default(omit) }}"
    capabilities: "{{ container.capabilities | default(omit) }}"
    cgroup_parent: "{{ container.cgroup_parent | default(omit) }}"
    cgroupns_mode: "{{ container.cgroupns_mode | default(omit) }}"
    cleanup: "{{ container.cleanup | default(omit) }}"
    client_cert: "{{ container.client_cert | default(omit) }}"
    tls_client_cert: "{{ container.tls_client_cert | default(omit) }}"
    cert_path: "{{ container.cert_path | default(omit) }}"
    client_key: "{{ container.client_key | default(omit) }}"
    tls_client_key: "{{ container.tls_client_key | default(omit) }}"
    key_path: "{{ container.key_path | default(omit) }}"
    command: "{{ container.command | default(omit) }}"
    command_handling: "{{ container.command_handling | default(omit) }}"
    comparisons: "{{ container.comparisons | default(omit) }}"
    container_default_behavior: "{{ container.container_default_behavior | default(omit) }}"
    cpu_period: "{{ container.cpu_period | default(omit) }}"
    cpu_quota: "{{ container.cpu_quota | default(omit) }}"
    cpu_shares: "{{ container.cpu_shares | default(omit) }}"
    cpus: "{{ container.cpus | default(omit) }}"
    cpuset_cpus: "{{ container.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ container.cpuset_mems | default(omit) }}"
    debug: "{{ container.debug | default(omit) }}"
    default_host_ip: "{{ container.default_host_ip | default(omit) }}"
    detach: "{{ container.detach | default(omit) }}"
    device_read_bps: "{{ container.device_read_bps | default(omit) }}"
    device_read_iops: "{{ container.device_read_iops | default(omit) }}"
    device_requests: "{{ container.device_requests | default(omit) }}"
    device_write_bps: "{{ container.device_write_bps | default(omit) }}"
    device_write_iops: "{{ container.device_write_iops | default(omit) }}"
    devices: "{{ container.devices | default(omit) }}"
    dns_opts: "{{ container.dns_opts | default(omit) }}"
    dns_search_domains: "{{ container.dns_search_domains | default(omit) }}"
    dns_servers: "{{ container.dns_servers | default(omit) }}"
    docker_host: "{{ container.docker_host | default(omit) }}"
    docker_url: "{{ container.docker_url | default(omit) }}"
    domainname: "{{ container.domainname | default(omit) }}"
    entrypoint: "{{ container.entrypoint | default(omit) }}"
    env: "{{ container.env | default(omit) }}"
    env_file: "{{ container.env_file | default(omit) }}"
    etc_hosts: "{{ container.etc_hosts | default(omit) }}"
    exposed_ports: "{{ container.exposed_ports | default(omit) }}"
    exposed: "{{ container.exposed | default(omit) }}"
    expose: "{{ container.expose | default(omit) }}"
    force_kill: "{{ container.force_kill | default(omit) }}"
    forcekill: "{{ container.forcekill | default(omit) }}"
    groups: "{{ container.groups | default(omit) }}"
    healthcheck: "{{ container.healthcheck | default(omit) }}"
    hostname: "{{ container.hostname | default(omit) }}"
    ignore_image: "{{ container.ignore_image | default(omit) }}"
    image_comparison: "{{ container.image_comparison | default(omit) }}"
    image_label_mismatch: "{{ container.image_label_mismatch | default(omit) }}"
    image_name_mismatch: "{{ container.image_name_mismatch | default(omit) }}"
    init: "{{ container.init | default(omit) }}"
    interactive: "{{ container.interactive | default(omit) }}"
    ipc_mode: "{{ container.ipc_mode | default(omit) }}"
    keep_volumes: "{{ container.keep_volumes | default(omit) }}"
    kernel_memory: "{{ container.kernel_memory | default(omit) }}"
    kill_signal: "{{ container.kill_signal | default(omit) }}"
    labels: "{{ container.labels | default(omit) }}"
    links: "{{ container.links | default(omit) }}"
    log_driver: "{{ container.log_driver | default(omit) }}"
    log_options: "{{ container.log_options | default(omit) }}"
    log_opt: "{{ container.log_opt | default(omit) }}"
    mac_address: "{{ container.mac_address | default(omit) }}"
    memory: "{{ container.memory | default(omit) }}"
    memory_reservation: "{{ container.memory_reservation | default(omit) }}"
    memory_swap: "{{ container.memory_swap | default(omit) }}"
    memory_swappiness: "{{ container.memory_swappiness | default(omit) }}"
    mounts: "{{ container.mounts | default(omit) }}"
    network_mode: "{{ container.network_mode | default(omit) }}"
    networks: "{{ container.networks | default(omit) }}"
    networks_cli_compatible: "{{ container.networks_cli_compatible | default(omit) }}"
    oom_killer: "{{ container.oom_killer | default(omit) }}"
    oom_score_adj: "{{ container.oom_score_adj | default(omit) }}"
    output_logs: "{{ container.output_logs | default(omit) }}"
    paused: "{{ container.paused | default(omit) }}"
    pid_mode: "{{ container.pid_mode | default(omit) }}"
    pids_limit: "{{ container.pids_limit | default(omit) }}"
    platform: "{{ container.platform | default(omit) }}"
    privileged: "{{ container.privileged | default(omit) }}"
    publish_all_ports: "{{ container.publish_all_ports | default(omit) }}"
    published_ports: "{{ container.published_ports | default(omit) }}"
    ports: "{{ container.ports | default(omit) }}"
    pull: "{{ container.pull | default(omit) }}"
    purge_networks: "{{ container.purge_networks | default(omit) }}"
    read_only: "{{ container.read_only | default(omit) }}"
    recreate: "{{ container.recreate | default(omit) }}"
    removal_wait_timeout: "{{ container.removal_wait_timeout | default(omit) }}"
    restart: "{{ container.restart | default(omit) }}"
    restart_policy: "{{ container.restart_policy | default(omit) }}"
    restart_retries: "{{ container.restart_retries | default(omit) }}"
    runtime: "{{ container.runtime | default(omit) }}"
    security_opts: "{{ container.security_opts | default(omit) }}"
    shm_size: "{{ container.shm_size | default(omit) }}"
    ssl_version: "{{ container.ssl_version | default(omit) }}"
    state: "{{ container.state | default(omit) }}"
    stop_signal: "{{ container.stop_signal | default(omit) }}"
    stop_timeout: "{{ container.stop_timeout | default(omit) }}"
    storage_opts: "{{ container.storage_opts | default(omit) }}"
    sysctls: "{{ container.sysctls | default(omit) }}"
    timeout: "{{ container.timeout | default(omit) }}"
    tls: "{{ container.tls | default(omit) }}"
    tls_hostname: "{{ container.tls_hostname | default(omit) }}"
    tmpfs: "{{ container.tmpfs | default(omit) }}"
    tty: "{{ container.tty | default(omit) }}"
    ulimits: "{{ container.ulimits | default(omit) }}"
    use_ssh_client: "{{ container.use_ssh_client | default(omit) }}"
    user: "{{ container.user | default(omit) }}"
    userns_mode: "{{ container.userns_mode | default(omit) }}"
    uts: "{{ container.uts | default(omit) }}"
    validate_certs: "{{ container.validate_certs | default(omit) }}"
    tls_verify: "{{ container.tls_verify | default(omit) }}"
    volume_driver: "{{ container.volume_driver | default(omit) }}"
    volumes_from: "{{ container.volumes_from | default(omit) }}"
    working_dir: "{{ container.working_dir | default(omit) }}"
