---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  become: true

- name: Create fail2ban jail.local
  template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: true
  become: true

