---

- name: Create Traefik config for {{ app.name }}
  delegate_to: "{{ network_svc.traefik.host }}"
  become: true
  ansible.builtin.template:
    src: traefik-app.yml.j2
    dest: "{{ hostvars[network_svc.traefik.host].common_dir }}/traefik/configs/app-{{ app.name }}.yml"
  when: app.traefik is defined
