---
- name: Load configs
  no_log: "{{ ci | default(false) }}"
  ansible.builtin.include_vars:
    dir: "{{ common_ansible_root }}/apps"
    ignore_unknown_extensions: true
    ignore_files:
      - _defaults.yml
    depth: 1
    name: _configs
  register: _load_configs

- ansible.builtin.fail:
    msg: "{{ _load_configs }}"
  when: _configs is undefined

- name: Load defaults
  ansible.builtin.include_vars:
    file: "{{ common_ansible_root }}/apps/_defaults.yml"
    name: _defaults
