---

- name: load all app manifests
  ansible.builtin.include_vars:
    dir: "{{ common_ansible_root }}/apps"
    extensions:
      - "yml"
    ignore_unknown_extensions: true
    name: apps
  no_log: true

- name: Set app variables
  ansible.builtin.set_fact:
    app: "{{ apps[run_app] | combine({'name': apps[run_app].name | default(run_app)}) }}"
  when: run_app is defined
