---
- ansible.builtin.fail: msg="Variable '_app' is not defined"
  when: _app is undefined

- name: Include load_configs task
  ansible.builtin.include_tasks: load_configs.yml
  when: _preprocessed is undefined

- name: Load app config for {{ _app }}
  ansible.builtin.set_fact:
    _app_config: "{{ _configs[_app] | mandatory }}"

- name: Set app name for {{ _app }}
  ansible.builtin.set_fact:
    _app_name: "{{ _app_config.name | default(_app) }}"

- name: Include create_db task
  tags: db
  ansible.builtin.include_tasks: create_db.yml
  when:
    - _app_config.db is defined

- name: Include create_container task
  tags: container
  ansible.builtin.include_tasks: create_container.yml
  when:
    - _app_config.container is defined

- name: Include create_traefik_config task
  tags: traefik
  ansible.builtin.include_tasks: create_traefik_config.yml
  when:
    - _app_config.traefik is defined

- name: Include create_uptime_config task
  tags: uptime
  ansible.builtin.include_tasks: create_uptime_config.yml
  when:
    - _app_config.uptime is defined

- name: Include create_dependents task
  tags: container
  ansible.builtin.include_tasks: create_dependents.yml
  when:
    - _app_config.dependents is defined
