apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-efk
  namespace: logging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-efk

  dataFrom:
    - extract:
        key: EFK_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
