---

apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json5: |-
    {
      platform: 'gitea',
      endpoint: 'https://git.sbbh.cloud/api/v1/',
      gitAuthor: 'Renovate Bot <renovate@sbbh.cloud>',
      username: 'renovate',
      timezone: "Australia/Melbourne",
      autodiscover: false,
      onboarding: false,
      persistRepoData: true,
      repositories: [
        "sysadm/homelab"
      ],
    }
