apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-renovate
  namespace: gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-renovate
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .renovate_token }}"
        GITHUB_COM_USER: "{{ .github_user }}"
        GITHUB_COM_TOKEN: "{{ .github_token }}"
        DOCKER_USER: "{{ .docker_user }}"
        DOCKER_PASSWORD: "{{ .docker_password }}"
        DOCKER_GHCR_IO_USERNAME: "{{ .github_user }}"
        DOCKER_GHCR_IO_PASSWORD: "{{ .github_token }}"
        DOCKER_LSCR_IO_USERNAME: "{{ .github_user }}"
        DOCKER_LSCR_IO_PASSWORD: "{{ .github_token }}"

  data:
    - secretKey: renovate_token
      remoteRef:
        key: RENOVATE_TOKEN
    - secretKey: github_user
      remoteRef:
        key: GITHUB_USER
    - secretKey: github_token
      remoteRef:
        key: GITHUB_TOKEN
    - secretKey: docker_user
      remoteRef:
        key: DOCKER_USER
    - secretKey: docker_password
      remoteRef:
        key: DOCKER_PASSWORD
