---
metube:
  host: services
  container:
    image: ghcr.io/alexta69/metube:2025.07.31
    ports:
      - 8081:8081
    env:
      TEMP_DIR: /cache
      STATE_DIR: /state
      DOWNLOAD_MODE: limited
      MAX_CONCURRENT_DOWNLOADS: "5"
      OUTPUT_TEMPLATE: "%(title)s_%(epoch)s.%(ext)s"
    volumes:
      - "/data/media/various/misc/new:/downloads"
      - "{{ common_data_dir }}/metube/cache:/cache"
      - "{{ common_data_dir }}/metube/state:/state"
