---
syncthing:
  host: vps
  container:
    image: ghcr.io/syncthing/syncthing:2.0.0-rc.24
    network_mode: host
    networks: []
    userns_mode: host
    volumes:
      - "{{ common_data_dir }}/syncthing/config:/var/syncthing/config"
      - "{{ common_data_dir }}/syncthing/data:/var/syncthing/data"
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
