---
vault:
  host: vps
  container:
    image: hashicorp/vault:1.20
    env:
      VAULT_ADDR: &addr https://100.94.245.44:8200
      VAULT_API_ADDR: *addr
      VAULT_ADDRESS: *addr
    ports:
      - 8200:8200
      - 8201:8201
    volumes:
      - "{{ common_data_dir }}/vault/logs:/vault/logs"
      - "{{ common_data_dir }}/vault/data:/vault/data"
      - "{{ common_data_dir }}/vault/config:/vault/config"
      - "{{ common_data_dir }}/vault/file:/vault/file"
      - "{{ common_data_dir }}/vault/certs:/certs"
    capabilities:
      - ipc_lock
    entrypoint: vault server -config /vault/config/config.hcl
