---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.13.12
    namespace: metallb
    includeCRDs: true
    releaseName: metallb

resources:
  - namespace.yaml
  - metallb-config.yaml
