---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  secret-karakeep:
    internal: true
    cmd: task run -- services/karakeep encryption_key={{.encryption_key}} meilisearch_master_key={{.meilisearch_master_key}} openai_key={{.openai_key}}
    vars:
      encryption_key:
        sh: bwget karakeep.sbbh.cloud encryption-key
      meilisearch_master_key:
        sh: bwget karakeep.sbbh.cloud meilisearch-master-key
      openai_key:
        sh: bwget karakeep.sbbh.cloud openai-key
