---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  k8s: { taskfile: ./k8s.yml, flatten: true }
  infra: { taskfile: ./infra.yml, flatten: true }
  media: { taskfile: ./media.yml, flatten: true }
  services: { taskfile: ./services.yml, flatten: true }

vars:
  VAULT_CMD: vault kv put
  PATH: ops

tasks:
  create:*:
    deps: [bw-unlock]
    vars:
      SECRET: "{{index .MATCH 0}}"
    cmds:
      - echo "Creating secret for {{.SECRET}}"
      - task: secret-{{.SECRET}}

  bw-unlock:
    internal: true
    run: once
    cmds:
      - bwunlock
    status:
      - test $(bww status 2> /dev/null | jq -r '.status') == "unlocked"

  run:
    cmd: "{{.CMD}}"
    vars:
      CMD: "{{.VAULT_CMD}} {{.PATH}}/{{.CLI_ARGS}}"
    prompt:
      - |-
        Running command:
        ---
        {{.CMD}}
        ---
        Continue?

  refresh:
    desc: Refresh external secrets
    cmd: |
      kubectl get externalsecret -A --no-headers -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name" |
        while read ns name; do kubectl annotate externalsecret "$name" -n "$ns" force-sync=$(date +%s) --overwrite; done
