---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - applications:
        - "*"
      clusters:
        - "*"
      namespaces:
        - "*"
      schedule: "* 5 * * *"
      duration: 1h
      kind: allow
      manualSync: true
      timeZone: Australia/Melbourne
