---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infra-repo
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: infra-repo
    template:
      engineVersion: v2
      data:
        type: git
        url: "{{ .URL }}"
        password: "{{ .PASSWORD }}"
        username: "{{ .USERNAME }}"
      templateFrom:
        - target: Labels
          literal: "argocd.argoproj.io/secret-type: repository"

  dataFrom:
    - extract:
        key: GIT_SECRETS
