---
fullnameOverride: argocd

configs:
  params:
    applicationsetcontroller.policy: "create-only"
    server.insecure: true
  cm:
    statusbadge.enabled: "true"
    resource.customizations.ignoreDifferences.all: |
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
      - /data/tls.crt
      - /data/tls.key
      jqPathExpressions:
      - .webhooks[].clientConfig.caBundle
      - .spec.template.metadata.annotations | with_entries(select(.key | test("^checksum")))
    # Enabling Helm chart rendering with Kustomize
    kustomize.buildOptions: --enable-helm

server:
  replicas: 2
  config:
    kustomize.buildOptions: "--enable-helm"

controller:
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1

applicationSet:
  replicaCount: 2

repoServer:
  replicas: 2
