---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json5: |-
    {
      platform: 'gitea',
      endpoint: 'https://git.sbbh.cloud/api/v1/',
      gitAuthor: 'Renovate Bot <renovate@sbbh.cloud>',
      username: 'renovate',
      autodiscover: false,
      onboardingConfig: {
        $schema: 'https://docs.renovatebot.com/renovate-schema.json',
        extends: ['config:base']
      },
      persistRepoData: true,
      repositories: [
        "sysadm/homelab"
      ],
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:35.32.0
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_DETECT_HOST_RULES_FROM_ENV
                  value: 'true'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: various-doppler-secret
                      key: RENOVATE_TOKEN
                - name: GITHUB_COM_USER
                  value: 'Subbeh'
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: various-doppler-secret
                      key: GITHUB_COM_TOKEN                      
                - name: DOCKER_GHCR_IO_USERNAME
                  value: 'Subbeh'
                - name: DOCKER_GHCR_IO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: various-doppler-secret
                      key: GITHUB_COM_TOKEN                      
                - name: DOCKER_LSCR_IO_USERNAME
                  value: 'Subbeh'
                - name: DOCKER_LSCR_IO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: various-doppler-secret
                      key: GITHUB_COM_TOKEN                      
                - name: DOCKER_USER
                  value: 'sterwindt'
                - name: DOCKER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: various-doppler-secret
                      key: DOCKER_PASSWORD                      
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json5'
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
