---

- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Load all container manifests
      tags: always
      ansible.builtin.include_role:
        name: apps
        tasks_from: load_vars
        apply:
          tags: always

    - name: Set fact with tags
      tags: always
      ansible.builtin.set_fact:
        run_container: "{{ ansible_run_tags[0] }}"

    - name: Add container host to temporary host group
      tags: always
      ansible.builtin.add_host:
        name: "{{ network_svc[run_container].host }}"
        groups: temp_group
      changed_when: false

- hosts: temp_group
  become: true
  gather_facts: true

  pre_tasks:
    - name: Verify SSH port
      tags: always
      ansible.builtin.include_tasks:
        file: ../tasks/ssh_port.yml
      vars:
        ansible_become: false

    - name: Gathering facts
      tags: always
      ansible.builtin.setup:

  tasks:
    - name: Include apps role
      tags: always
      ansible.builtin.include_role:
        name: apps
        apply:
          tags: always
      vars:
        run_container: "{{ hostvars['localhost']['run_container'] }}"          
