---
- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Set app fact
      ansible.builtin.set_fact:
        _run_apps: "{{ app | split }}"

    - name: Load app configs
      ansible.builtin.include_role:
        name: apps
        tasks_from: load_configs

    - name: Include app role
      ansible.builtin.include_role:
        name: apps
      with_items: "{{ _run_apps }}"
      loop_control:
        loop_var: app_item
      vars:
        _app: "{{ app_item }}"
        _tags: "{{ ansible_run_tags }}"
        _preprocessed: true
