---

- hosts: bastion
  gather_facts: false
  become: true

  vars:
    security_ssh_port: 3322
    firewall_allowed_tcp_ports:
      - 22
      - 3322
      - 80
      - 443
      - "{{ network_svc.portainer.agent_port }}"
    firewall_allowed_udp_ports:
      - 4242  # syslog
      - 41641 # tailscale
      - 3478  # tailscale

    docker_users:
      - "{{ common_user }}"

    borg_source_directories:
      - '{{ common_dir }}'
    borgmatic_cron_hour: 02
    borgmatic_cron_minute: 00

  pre_tasks:
    - name: Verify SSH port
      tags: [ always, pretasks ]
      ansible.builtin.import_tasks:
        file: ../tasks/check_port.yml
      vars:
        ansible_become: false

    - name: Gathering facts
      tags: always
      ansible.builtin.setup:

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: ../tasks/handlers.yml

  tasks:
    - name: Import bootstrap role
      tags: bootstrap
      ansible.builtin.import_role:
        name: bootstrap

    - name: Enable firewall
      tags: firewall
      ansible.builtin.import_role:
        name: geerlingguy.firewall

    - name: Install Docker
      tags: docker
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Import Borg backups role
      tags: borg
      ansible.builtin.import_role:
        name: borg

    - name: Import Traefik role
      tags: traefik
      ansible.builtin.import_role:
        name: traefik

    - name: Import CrowdSec role
      tags: crowdsec
      ansible.builtin.import_role:
        name: crowdsec

    - name: Deploy containers
      tags: apps
      ansible.builtin.include_role:
        name: apps
        apply:
          tags: always
      vars:
        run_app: "{{ item }}"
      with_items:
        - portainer_agent_bastion
        - endlessh
