---

- hosts: bastion
  gather_facts: false
  become: true

  vars:
    security_ssh_port: 3322
    firewall_allowed_tcp_ports:
      - 22
      - 3322
      - 80
      - 443
      - "{{ network_svc.portainer.agent_port }}"
    firewall_allowed_udp_ports:
      - 4242  # syslog
      - 41641 # tailscale
      - 3478  # tailscale

    docker_users:
      - "{{ common_user }}"

    borg_source_directories:
      - '{{ common_dir }}'
    borg_hc_ping_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36353263643163323966653061653832626562383532623532333533393832353131343564663961
          3530386131353431656239666366616461363239636433330a366630616232626538313036393166
          39356638313764626631623935633830396233616236353432643631613633633732393963623362
          3339656430636562300a383764633935353437356632616133613834613431316263396433323437
          31613030616139343731623533366638616236643639636265313131613335643064386436366461
          32363237343033396631366635393333323831363838363866313032376538666434643761656361
          396361343630626466633239333230313562
    borgmatic_timer_hour: 02
    borgmatic_timer_minute: 10

  pre_tasks:
    - name: Verify SSH port
      tags: [ always, pretasks ]
      ansible.builtin.import_tasks:
        file: ../tasks/check_port.yml
      vars:
        ansible_become: false

    - name: Gathering facts
      tags: always
      ansible.builtin.setup:

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: ../tasks/handlers.yml

  tasks:
    - name: Import bootstrap role
      tags: bootstrap
      ansible.builtin.import_role:
        name: bootstrap

    - name: Enable firewall
      tags: firewall
      ansible.builtin.import_role:
        name: geerlingguy.firewall

    - name: Install Docker
      tags: docker
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Import Borg backups role
      tags: borg
      ansible.builtin.import_role:
        name: borg

    - name: Import Traefik role
      tags: traefik
      ansible.builtin.import_role:
        name: traefik

    - name: Import CrowdSec role
      tags: crowdsec
      ansible.builtin.import_role:
        name: crowdsec

    - name: Deploy containers
      tags: apps
      ansible.builtin.include_role:
        name: apps
        apply:
          tags: always
      vars:
        run_app: "{{ item }}"
      with_items:
        - portainer_agent_bastion
        - endlessh
