---

- hosts: "pve-nuc-01"
  gather_facts: false

  vars:
    cloudimg_src: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img
    cloudimg: "{{ cloudimg_src | basename }}"
    iso_dir: /mnt/pve/nas/template/iso
    template: "/root/templates/{{ cloudimg | regex_replace('img$', 'qcow2') }}"
    ssh_keys: "https://raw.githubusercontent.com/Subbeh/dotfiles/master/keys"
    vm_user: "{{ common_user }}"
    vm_passwd: "{{ common_pass }}"
    vm_id: 9000
    vm_name: ubuntu-2204-cloudinit-template
    vm_mem: 1024
    vm_cores: 1
    vm_size: 3G
    vm_storage: nas

  tasks:

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ iso_dir }}"
        - "{{ template | dirname }}"

    - name: Download cloud-init image
      ansible.builtin.get_url:
        url: "{{ cloudimg_src }}"
        dest: "{{ iso_dir }}/{{ cloudimg }}"

    - name: Copy cloud-init image to template
      ansible.builtin.copy:
        src: "{{ iso_dir }}/{{ cloudimg }}"
        dest: "{{ template }}"
        remote_src: yes

    - name: Ensure that libguestfs-tools is installed
      ansible.builtin.apt:
        name: libguestfs-tools
        state: present
        update_cache: yes

    - name: Download public SSH keys
      ansible.builtin.get_url:
        url: '{{ ssh_keys }}'
        dest: /tmp/authorized_keys

    - name: Create sudoers file
      ansible.builtin.copy:
        content: "{{ vm_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: /tmp/sudoers

    - name: Provision image - update
      ansible.builtin.command: virt-customize -a {{ template }} --update

    - name: Provision image - install qemu-guest-agent
      ansible.builtin.command: virt-customize -a {{ template }} --install qemu-guest-agent

    - name: Provision image - add user
      ansible.builtin.command: virt-customize -a {{ template }} --run-command "useradd -m --shell /bin/bash {{ vm_user }}"
      register: command_result
      failed_when: "command_result.rc != 0 and 'already exists' not in command_result.stderr"

    - name: Provision image - set user password
      ansible.builtin.command: virt-customize -a {{ template }} --password {{ vm_user }}:password:{{ vm_passwd }}

    - name: Provision image - create .ssh folder for user
      ansible.builtin.command: virt-customize -a {{ template }} --run-command 'mkdir -p /home/{{ vm_user }}/.ssh'

    - name: Provision image - add public SSH key
      ansible.builtin.command: virt-customize -a {{ template }} --ssh-inject {{ vm_user }}:file:/tmp/authorized_keys

    - name: Provision image - chown user home directory
      ansible.builtin.command: virt-customize -a {{ template }} --run-command 'chown -R {{ vm_user }}:{{ vm_user }} /home/{{ vm_user }}'

    - name: Provision image - create sudoers file for user
      ansible.builtin.command: virt-customize -a {{ template }} --upload /tmp/sudoers:/etc/sudoers.d/{{ vm_user }}

    - name: Provision image - chmod sudoers file
      ansible.builtin.command: virt-customize -a {{ template }} --run-command 'chmod 0440 /etc/sudoers.d/{{ vm_user }}'

    - name: Provision image - chown sudoers file
      ansible.builtin.command: virt-customize -a {{ template }} --run-command 'chown root:root /etc/sudoers.d/{{ vm_user }}'

    - name: Provision image - clear machine-id so clones get unique mac address
      ansible.builtin.command: virt-customize -a {{ template }} --run-command '>/etc/machine-id'

    - name: Create vm
      ansible.builtin.command: "qm create {{ vm_id }} --name '{{ vm_name }}' --memory {{ vm_mem }} --cores {{ vm_cores }} --net0 virtio,bridge=vmbr0"

    - name: Create vm - import cloud-init disk
      ansible.builtin.command: "qm importdisk {{ vm_id }} {{ template }} {{ vm_storage }}"

    - name: Create vm - attach cloud-init disk
      ansible.builtin.command: "qm set {{ vm_id }} --scsihw virtio-scsi-pci --scsi0 {{ vm_storage }}:{{ vm_id }}/vm-{{ vm_id }}-disk-0.raw"

    - name: Create vm - assign bootdisk
      ansible.builtin.command: "qm set {{ vm_id }} --boot c --bootdisk scsi0"

    - name: Create vm - add cloud-init support
      ansible.builtin.command: "qm set {{ vm_id }} --ide2 {{ vm_storage }}:cloudinit"

    - name: Create vm - attach serial console
      ansible.builtin.command: "qm set {{ vm_id }} --serial0 socket --vga serial0"

    - name: Create vm - enable KVM agent
      ansible.builtin.command: "qm set {{ vm_id }} --agent enabled=1"

    - name: Create vm - resize disk
      ansible.builtin.command: "qm resize {{ vm_id }} scsi0 {{ vm_size }}"

    - name: Create vm - convert to template
      ansible.builtin.command: "qm template {{ vm_id }}"
