---

- hosts: hl-services
  gather_facts: false
  become: true

  vars:
    borg_source_directories:
      - '{{ common_dir }}'
    borgmatic_cron_hour: 02
    borgmatic_cron_minute: 10
    borgmatic_hooks:
      before_backup:
        - echo "`date` - Starting backup."
      after_backup:
        - echo "`date` - Backup created."
      on_error:
        - echo "`date` - Error while creating a backup."
      postgresql_databases:
        - name: all
          hostname: localhost
          username: "{{ common_user }}"
          password: "{{ postgres_pass }}"

  pre_tasks:
    - name: Verify SSH port
      tags: [ always, pretasks ]
      ansible.builtin.import_tasks:
        file: ../tasks/ssh_port.yml
      vars:
        ansible_become: false

    - name: Gathering facts
      tags: always
      ansible.builtin.setup:

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: ../tasks/handlers.yml

  tasks:
    - name: Import bootstrap role
      tags: bootstrap
      ansible.builtin.import_role:
        name: bootstrap

    - name: Include Borg backups role
      tags: borg
      ansible.builtin.include_role:
        name: borg
        apply:
          tags: always

    - name: Include Authentik role
      tags: authentik
      ansible.builtin.include_role:
        name: authentik
        apply:
          tags: always

    - name: Create Portainer container
      tags: portainer
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "portainer"

    - name: Create Cloudflare ddns container
      tags: cloudflare
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "cloudflare-ddns"

    - name: Create Drone container
      tags: drone
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "drone"

    - name: Create Gitea container
      tags: gitea
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "gitea"

    - name: Create Overseerr container
      tags: overseerr
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "overseerr"

    - name: Create Tautulli container
      tags: tautulli
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "tautulli"

    - name: Create Openspeedtest container
      tags: openspeedtest
      ansible.builtin.import_tasks: ../tasks/run_container.yml
      vars:
        run_container: "openspeedtest"
