---
- hosts: services
  gather_facts: true
  become: true

  vars:
    bootstrap:
      node_exporter: true

  tasks:
    - name: Run bootstrap role
      ansible.builtin.import_role:
        name: bootstrap
