---
# 0. destroy
# 1. vm
# 2. bootstrap
#   2.1 bootstrap_custom
#   2.2 runtime
#   2.3 k8s_packages
#   2.4 vip
# 3. cluster
#   3.1 cluster_init
#   3.2 kubeconfig
#   3.3 tools
#   3.4 clone
#   3.5 cluster_join
#   3.6 configure
# 4. deploy
#   4.1 calico
#   4.2 crds
#   4.3 eso
#   4.4 argocd

- hosts: k8s
  tags: [never, destroy]
  gather_facts: false
  become: false
  serial: 1

  tasks:
    - block:
        - ansible.builtin.debug: msg="DESTROYING CLUSTER ..."
        - name: Pausing for 5 seconds...
          ansible.builtin.pause:
            seconds: 5
      run_once: true

    - name: k8s | Destroy VMs
      ansible.builtin.import_role:
        name: pve
        tasks_from: destroy_vm

- hosts: k8s
  tags: [never, vm]
  gather_facts: false
  become: false
  serial: 3

  tasks:
    - name: k8s | Create VMs from template
      ansible.builtin.import_role:
        name: pve
        tasks_from: clone_template

- hosts: k8s
  tags: never
  gather_facts: true
  become: true

  tasks:
    - name: k8s | Bootstrap nodes
      tags: [bootstrap]
      ansible.builtin.import_role:
        name: bootstrap

    - name: k8s-masters | Bootstrap nodes
      tags: [bootstrap, bootstrap_custom]
      ansible.builtin.import_role:
        name: bootstrap
      vars:
        bootstrap:
          pkg_install: true
          profile_files_custom: true
        bootstrap_pkg_pip_extra:
          - kubernetes
        bootstrap_profile_custom_root: |
          alias k=kubectl
          export KUBECONFIG=/etc/kubernetes/admin.conf
      when: inventory_hostname in groups['k8s-masters']

    - name: k8s-workers | Bootstrap nodes
      tags: [bootstrap, bootstrap_custom]
      ansible.builtin.import_role:
        name: bootstrap
      vars:
        bootstrap:
          mounts: true
        bootstrap_mounts:
          - src: LABEL=k8s
            path: /srv/longhorn
            type: ext4
      when: inventory_hostname in groups['k8s-workers']

    - name: k8s | Install container runtime
      tags: [bootstrap, runtime]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: container_runtime

    - name: k8s | Install kubernetes packages
      tags: [bootstrap, k8s_packages]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: k8s_packages

    - name: k8s-masters | Install kube-vip
      tags: [bootstrap, vip]
      ansible.builtin.import_role:
        name: k8s/resources
        tasks_from: kube_vip
      when: inventory_hostname in groups['k8s-masters']

    - name: k8s-master-01 | Install tools
      tags: [bootstrap, tools]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: tools
      when: inventory_hostname == 'k8s-master-01'

- hosts: k8s-master-01
  tags: never
  gather_facts: true
  become: true
  any_errors_fatal: true

  tasks:
    - name: k8s-master-01 | Initialize cluster
      tags: [cluster, cluster_init]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: cluster_init

    - name: k8s-master-01 | Fetch kubeconfig
      tags: [cluster, kubeconfig]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: kubeconfig

- hosts: k8s
  tags: never
  gather_facts: true
  become: true
  serial: 1

  tasks:
    - name: k8s | Join cluster
      tags: [cluster, cluster_join]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: cluster_join

    - name: k8s | Configure nodes
      tags: [cluster, configure]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: configure

- hosts: k8s-master-01
  tags: never
  gather_facts: true
  become: true
  any_errors_fatal: true

  environment:
    KUBECONFIG: "{{ k8s.kubeconfig }}"

  tasks:
    - name: k8s-master-01 | Clone git repository
      tags: [deploy, clone]
      ansible.builtin.import_role:
        name: k8s/cluster
        tasks_from: clone_repo

    - name: k8s-master-01 | Deploy Calico CNI
      tags: [deploy, calico]
      ansible.builtin.import_role:
        name: k8s/resources
        tasks_from: calico

    - name: k8s-master-01 | Deploy CRDs
      tags: [deploy, crds]
      ansible.builtin.import_role:
        name: k8s/resources
        tasks_from: crds

    - name: k8s-master-01 | Deploy Exernal Secrets Operator
      tags: [deploy, eso]
      ansible.builtin.import_role:
        name: k8s/resources
        tasks_from: eso

    - name: k8s-master-01 | Deploy ArgoCD
      tags: [deploy, argocd]
      ansible.builtin.import_role:
        name: k8s/resources
        tasks_from: argocd
