---
- hosts: test
  gather_facts: true
  become: true

  vars:
    bootstrap:
      packages: true
      # user: true
      # system: true
      # network: true
      # ntp: true
      # profile: true
      # locale: true
      filesystem: true

    bootstrap_user:
      name: "{{ common_user }}"
      password: "{{ common_pass }}"

    bootstrap_pkg_rm: []
    bootstrap_pkg: []
    bootstrap_pkg_extra:
      - nfs-common
      - sudo
      - vim
    bootstrap_pkg_pip: []
    bootstrap_pkg_pip_extra: []
    bootstrap_pkg_microcode: true
    bootstrap_pkg_unattended_upgrades: true

    bootstrap_sys_disable_swap: true
    bootstrap_sys_grub_config: []
    bootstrap_sys_disable_svc: []
    bootstrap_sys_disable_cloudinit: false
    bootstrap_sys_cloudinit_options: []

    bootstrap_net_hostname: "{{ inventory_hostname_short }}.{{ network_domain.tld_local }}"
    bootstrap_net_set_hosts_file: true
    bootstrap_net_set_dns: true
    bootstrap_net_dns_server: "{{ network_svc.dns.ip }}"
    bootstrap_net_dns_domain: "{{ network_domain.tld_local }}"

    bootstrap_ssh_authorizedkeys:
      - "{{ vault_ssh_keys.pub.master }}"
      - "{{ vault_ssh_keys.pub.drone }}"

    bootstrap_ntp_timezone: "{{ common_timezone }}"
    bootstrap_ntp_server: "{{ network_svc.gw.ip }}"

    bootstrap_profile_config:
      - file: bashrc
        dest: ".bashrc"
      - file: vimrc
        dest: ".vimrc"

    bootstrap_profile_defaults:
      - editor: /usr/bin/vim
    bootstrap_locales:
      - "{{ common_locale }}"

    bootstrap_fs_directories:
      - "{{ common_dir }}"
      - "{{ common_data_dir }}"
    bootstrap_fs_mounts:
      - src: "nas:/volume1/media"
        dest: "{{ common_data_dir }}"

  tasks:
    - name: Import bootstrap role
      tags: bootstrap
      ansible.builtin.import_role:
        name: bootstrap
