---
- hosts: "{{ ansible_limit | default(groups['pve'][0]) }}"
  gather_facts: true

  vars:
    pve_template:
      name: debian-12-template
      vmid: 1000
      image: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2

  tasks:
    - name: Create template
      tags: [never, template]
      ansible.builtin.import_role:
        name: pve
        tasks_from: create_template
