---

- hosts: services
  gather_facts: false
  become: true

  vars:
    docker_users:
      - "{{ common_user }}"

    packages_custom:
      - postgres-client

    borg_source_directories:
      - '{{ common_dir }}'
    borg_hc_ping_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38643637643233373763663236363263653262646230653731393537633133303839383361376331
          3236343066313039303163383834666535346533383735320a326463633532336339636231353338
          65333032386139653931353333643262313332666633636362656238333136353233393939643331
          3637666536363562620a643863386438313031373232636335346437373562303338343235326632
          30393538326234363362316565623738356531626235616262613339353530646564393333663133
          39613237393565666463303861393463366262346535336636326561633530376133326135313931
          626337333138313462373335316366666536
    borgmatic_timer_hour: 02
    borgmatic_timer_minute: 20
    borgmatic_hooks:
      before_backup:
        - echo "`date` - Starting backup."
      after_backup:
        - echo "`date` - Backup created."
      on_error:
        - echo "`date` - Error while creating a backup."
      postgresql_databases:
        - name: all
          hostname: localhost
          username: "{{ common_user }}"
          password: "{{ postgres_pass }}"
      healthchecks:
        ping_url: "{{ borg_hc_ping_url }}"

  pre_tasks:
    - name: Verify SSH port
      tags: [ always, pretasks ]
      ansible.builtin.import_tasks:
        file: ../tasks/check_port.yml
      vars:
        ansible_become: false

    - name: Gathering facts
      tags: always
      ansible.builtin.setup:

  handlers:
    - name: Import common handlers
      ansible.builtin.import_tasks: ../tasks/handlers.yml

  tasks:
    - name: Import bootstrap role
      tags: bootstrap
      ansible.builtin.import_role:
        name: bootstrap

    - name: Install Docker
      tags: docker
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Import Borg backups role
      tags: borg
      ansible.builtin.import_role:
        name: borg

    - name: Import Authentik role
      tags: authentik
      ansible.builtin.import_role:
        name: authentik

    - name: Deploy containers
      tags: apps
      ansible.builtin.include_role:
        name: apps
        apply:
          tags: always
      vars:
        run_app: "{{ item }}"
      with_items:
        - postgres
        - redis
        - portainer
        - gitea
        - overseerr
        - tautulli
        - openspeedtest
        - uptimekuma
        - wizarr
