---

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
