---

- name: load all container manifests
  ansible.builtin.include_vars:
    dir: "{{ common_ansible_root }}/containers"
    extensions:
      - "yml"
    ignore_unknown_extensions: true
    name: containers
  no_log: true

- name: Create container {{ run_container }}
  community.docker.docker_container:
    # use defaults
    name: "{{ run_container }}"
    image: "{{ containers[run_container].image }}"
    networks: "{{ containers[run_container].networks | default(containers['defaults'].networks) }}"
    restart_policy: "{{ containers[run_container].restart_policy | default(containers['defaults'].restart_policy) }}"
    state: "{{ containers[run_container].state | default(containers['defaults'].state) }}"
    log_driver: "{{ containers[run_container].log_driver | default(containers['defaults'].log_driver) }}"
    log_options: "{{ containers[run_container].log_options | default(containers['defaults'].log_options) }}"
    security_opts: "{{ containers[run_container].security_opts | default(containers['defaults'].security_opts) }}"
    volumes: "{{ containers[run_container].volumes | default([]) + containers['defaults'].volumes }}"
    env: "{{ containers['defaults'].environment | ansible.builtin.combine(containers[run_container].environment | default([]), list_merge='replace') }}"

    # misc
    exposed_ports: "{{ containers[run_container].exposed_ports | default(omit) }}"
    ports: "{{ containers[run_container].ports | default(omit) }}"
    hostname: "{{ containers[run_container].hostname | default(omit) }}"
    shm_size: "{{ containers[run_container].shm_size | default(omit) }}"
    command: "{{ containers[run_container].command | default(omit) }}"
    api_version: "{{ containers[run_container].api_version | default(omit) }}"
    auto_remove: "{{ containers[run_container].auto_remove | default(omit) }}"
    blkio_weight: "{{ containers[run_container].blkio_weight | default(omit) }}"
    cacert_path: "{{ containers[run_container].cacert_path | default(omit) }}"
    capabilities: "{{ containers[run_container].capabilities | default(omit) }}"
    cert_path: "{{ containers[run_container].cert_path | default(omit) }}"
    cleanup: "{{ containers[run_container].cleanup | default(omit) }}"
    cpu_period: "{{ containers[run_container].cpu_period | default(omit) }}"
    cpu_quota: "{{ containers[run_container].cpu_quota | default(omit) }}"
    cpuset_cpus: "{{ containers[run_container].cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ containers[run_container].cpuset_mems | default(omit) }}"
    cpu_shares: "{{ containers[run_container].cpu_shares | default(omit) }}"
    detach: "{{ containers[run_container].detach | default(omit) }}"
    devices: "{{ containers[run_container].devices | default(omit) }}"
    dns_search_domains: "{{ containers[run_container].dns_search_domains | default(omit) }}"
    dns_servers: "{{ containers[run_container].dns_servers | default(omit) }}"
    docker_host: "{{ containers[run_container].docker_host | default(omit) }}"
    domainname: "{{ containers[run_container].domainname | default(omit) }}"
    entrypoint: "{{ containers[run_container].entrypoint | default(omit) }}"
    etc_hosts: "{{ containers[run_container].etc_hosts | default(omit) }}"
    force_kill: "{{ containers[run_container].force_kill | default(omit) }}"
    groups: "{{ containers[run_container].groups | default(omit) }}"
    ignore_image: "{{ containers[run_container].ignore_image | default(omit) }}"
    interactive: "{{ containers[run_container].interactive | default(omit) }}"
    ipc_mode: "{{ containers[run_container].ipc_mode | default(omit) }}"
    keep_volumes: "{{ containers[run_container].keep_volumes | default(omit) }}"
    kernel_memory: "{{ containers[run_container].kernel_memory | default(omit) }}"
    key_path: "{{ containers[run_container].key_path | default(omit) }}"
    kill_signal: "{{ containers[run_container].kill_signal | default(omit) }}"
    labels: "{{ containers[run_container].labels | default(omit) }}"
    links: "{{ containers[run_container].links | default(omit) }}"
    mac_address: "{{ containers[run_container].mac_address | default(omit) }}"
    memory: "{{ containers[run_container].memory | default(omit) }}"
    memory_reservation: "{{ containers[run_container].memory_reservation | default(omit) }}"
    memory_swap: "{{ containers[run_container].memory_swap | default(omit) }}"
    memory_swappiness: "{{ containers[run_container].memory_swappiness | default(omit) }}"
    network_mode: "{{ containers[run_container].network_mode | default(omit) }}"
    oom_killer: "{{ containers[run_container].oom_killer | default(omit) }}"
    oom_score_adj: "{{ containers[run_container].oom_score_adj | default(omit) }}"
    paused: "{{ containers[run_container].paused | default(omit) }}"
    pid_mode: "{{ containers[run_container].pid_mode | default(omit) }}"
    privileged: "{{ containers[run_container].privileged | default(omit) }}"
    published_ports: "{{ containers[run_container].published_ports | default(omit) }}"
    pull: "{{ containers[run_container].pull | default(omit) }}"
    purge_networks: "{{ containers[run_container].purge_networks | default(omit) }}"
    read_only: "{{ containers[run_container].read_only | default(omit) }}"
    recreate: "{{ containers[run_container].recreate | default(omit) }}"
    restart: "{{ containers[run_container].restart | default(omit) }}"
    restart_retries: "{{ containers[run_container].restart_retries | default(omit) }}"
    ssl_version: "{{ containers[run_container].ssl_version | default(omit) }}"
    stop_signal: "{{ containers[run_container].stop_signal | default(omit) }}"
    stop_timeout: "{{ containers[run_container].stop_timeout | default(omit) }}"
    sysctls: "{{ containers[run_container].sysctls | default(omit) }}"
    timeout: "{{ containers[run_container].timeout | default(omit) }}"
    tls: "{{ containers[run_container].tls | default(omit) }}"
    tls_hostname: "{{ containers[run_container].tls_hostname | default(omit) }}"
    tls_verify: "{{ containers[run_container].tls_verify | default(omit) }}"
    tmpfs: "{{ containers[run_container].tmpfs | default(omit) }}"
    trust_image_content: "{{ containers[run_container].trust_image_content | default(omit) }}"
    tty: "{{ containers[run_container].tty | default(omit) }}"
    ulimits: "{{ containers[run_container].ulimits | default(omit) }}"
    user: "{{ containers[run_container].user | default(omit) }}"
    userns_mode: "{{ containers[run_container].userns_mode | default(omit) }}"
    uts: "{{ containers[run_container].uts | default(omit) }}"
    volume_driver: "{{ containers[run_container].volume_driver | default(omit) }}"
    volumes_from: "{{ containers[run_container].volumes_from | default(omit) }}"
    working_dir: "{{ containers[run_container].working_dir | default(omit) }}"
  register: _result
  changed_when: false
