---

- name: Debug
  ansible.builtin.debug:
    msg: "TEST {{ ansible_connection }}"

- name: Check SSH port
  when:
    - ansible_connection != 'community.docker.docker'
    - ansible_connection != 'local'
  block:
    - name: TEST
      ansible.builtin.debug:
        msg: "{{ ansible_connection }}"

    - name: Set ansible SSH host
      ansible.builtin.set_fact:
        _ssh_host: "{{ ansible_host | default(inventory_hostname) }}"

    - name: Register current SSH port
      ansible.builtin.set_fact:
        _configured_ssh_port: "{{ ansible_port | default(22) }}"

    - name: Check if we can connect using the configured port
      delegate_to: "localhost"
      register: _status
      failed_when: false
      ignore_errors: true
      ansible.builtin.wait_for:
        host: "{{ _ssh_host | default(omit) }}"
        port: "{{ _configured_ssh_port | default(omit) }}"
        timeout: 5

    - name: Change current SSH port to configured SSH port
      ansible.builtin.set_fact:
        ansible_port: "{{ security_ssh_port }}"
      when: _status.state is defined and _status.state == "started"

    - name: Check if we can connect using the default port
      delegate_to: "localhost"
      register: _status_default
      failed_when: false
      ignore_errors: true
      ansible.builtin.wait_for:
        host: "{{ _ssh_host }}"
        port: "22"
        timeout: 5
      when: _status.state is not defined

    - name: Change to port 22 for this session
      ansible.builtin.set_fact:
        ansible_port: "22"
      when: _status_default.state is defined and _status_default.state == "started"

    - ansible.builtin.fail:
        msg: Unable to connect to host
      when:
        - _status.state is not defined
        - _status_default.state is not defined
