---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  refresh:
    desc: Annotate Git repository and refresh cluster
    cmd: kubectl annotate gitrepository flux-system -n flux-system reconcile.fluxcd.io/requestedAt="$(date +%Y-%m-%dT%H:%M:%SZ)" --overwrite
