---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  github-dependencies:
    desc: Generate cluster dependencies
    cmds:
      - task: generate-deploy-key
      - task: add-github-deploy-key
      - task: generate-github-webhook-token

  generate-deploy-key:
    desc: Generate Github deploy key
    cmd: ssh-keygen -t ecdsa -b 521 -C "deploy-key" -f {{.SECRET_DIR}}/github-deploy.key -q -P ""
    status:
      - test -f {{.SECRET_DIR}}/github-deploy.key

  add-github-deploy-key:
    desc: Add or update deploy key in GitHub repository
    cmd: |
      if gh repo deploy-key list | grep -q "Flux Deploy Key"; then
        echo "Deploy key already exists, updating..."
        KEY_ID=$(gh repo deploy-key list --json id,title | jq -r '.[] | select(.title == "Flux Deploy Key") | .id')
        gh repo deploy-key delete $KEY_ID
      fi
      gh repo deploy-key add {{.SECRET_DIR}}/github-deploy.key.pub --title "Flux Deploy Key" --allow-write
    preconditions:
      - test -f {{.SECRET_DIR}}/github-deploy.key.pub
      - which gh jq

  generate-github-webhook-token:
    desc: Generate Github webhook token
    cmd: python -c "import secrets; print(secrets.token_hex(16), end='')" > {{.SECRET_DIR}}/github-webhook-token.txt
    status:
      - test -f {{.SECRET_DIR}}/github-webhook-token.txt
