---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .wg_private_key }}"
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .control_server_key }}"
  dataFrom:
    - extract:
        key: ops/infra/gluetun
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret qbittorrent-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .control_server_key }}"
  dataFrom:
    - extract:
        key: ops/infra/gluetun
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        MAM_ID: "{{ .mam_id }}"
  dataFrom:
    - extract:
        key: ops/media/qbittorrent
