---
- name: Check for existing bouncer
  ansible.builtin.command: docker exec -t crowdsec cscli bouncers list -o raw
  changed_when: false
  register: _bouncers

- name: Delete existing bouncer
  ansible.builtin.command: docker exec -t crowdsec cscli bouncers delete {{ crowdsec_bouncer }}
  when: crowdsec_bouncer in _bouncers.stdout
  changed_when: false

- name: Create bouncer
  ansible.builtin.command: docker exec -t crowdsec cscli bouncers add {{ crowdsec_bouncer }} -o raw
  register: _api_key
  changed_when: false

- name: Register API key
  ansible.builtin.set_fact:
    _crowdsec_bouncer_api_key: "{{ _api_key.stdout }}"

- ansible.builtin.fail:
    msg: _crowdsec_bouncer_api_key not specified
  when:
    - _crowdsec_bouncer_api_key == ""
