---

- name: Create crowdsec container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: crowdsec

- name: Enroll into CrowdSec hub
  ansible.builtin.shell: |
    docker exec -t crowdsec cscli console enroll {{ crowdsec_instance_id }}
  changed_when: false
  when: crowdsec_hub

- name: Copy acquis.yaml to server
  ansible.builtin.copy:
    src: acquis.yaml
    dest: "{{ common_dir }}/crowdsec/config/"
    mode: 0600
  notify: restart crowdsec

- name: Copy profiles.yaml to server
  ansible.builtin.copy:
    src: profiles.yaml
    dest: "{{ common_dir }}/crowdsec/config/"
    mode: 0600
  notify: restart crowdsec

- name: Copy plex-whitelist.yaml to server
  ansible.builtin.copy:
    src: plex-whitelist.yaml
    dest: '{{ common_dir }}/crowdsec/config/parsers/s01-parse/'
    mode: 0600
  notify: restart crowdsec

- name: Copy custom whitelists to server
  ansible.builtin.template:
    src: custom-whitelists.yaml.j2
    dest: "{{ common_dir }}/crowdsec/config/parsers/s02-enrich/custom-whitelists.yaml"
    mode: 0600
  notify: restart crowdsec

- name: Copy notifications config for Discord alerts
  ansible.builtin.template:
    src: discord.yaml.j2
    dest: "{{ common_dir }}/crowdsec/config/notifications/discord.yaml"
    mode: 0600
    variable_start_string: "[["
    variable_end_string: "]]"
  notify: restart crowdsec
