---

- name: Include bouncer task for Traefik bouncer
  ansible.builtin.include_tasks: bouncer.yml
  vars:
    crowdsec_bouncer: traefik-bouncer

- name: Create traefik-cs-bouncer container
  ansible.builtin.include_role:
    name: apps
  vars:
    run_app: "traefik-cs-bouncer"
