---
- name: Include bouncer task for Traefik bouncer
  ansible.builtin.include_tasks: bouncer.yml
  vars:
    crowdsec_bouncer: traefik-bouncer

- name: Copy traefik middleware over
  ansible.builtin.template:
    src: crowdsec-traefik-bouncer.yaml.j2
    dest: /opt/app_data/traefik/configs/middleware-crowdsec.yml
  changed_when: false
