---

- name: Update CrowdSec hub
  no_log: "{{ false if debug | default(true) }}"
  ansible.builtin.shell: |
    docker exec -t crowdsec cscli hub update
    docker exec -t crowdsec cscli hub upgrade --force
  changed_when: false
