---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: docker.io/crocodilestick/calibre-web-automated
              # renovate doesn't like versioning scheme, so just lock the latest
              tag: latest@sha256:577e846f104fd21453ef306eefb4a95dd95b3b9ddd2463a150944494284da0fd
            env:
              CACHE_DIR: /cache
              PUID: 1000
              PGID: 1000
              NETWORK_SHARE_MODE: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true # dumb s6 image
              # capabilities: { drop: ['ALL'] } # dumb s6 image needs to start as root and then it chowns and drops capabilities
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi
    # defaultPodOptions: # dumb s6 image
    #   automountServiceAccountToken: false
    #   enableServiceLinks: false
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: 'OnRootMismatch'

    service:
      app:
        ports:
          http:
            port: 8083

    route:
      app:
        hostnames: ["calibre.${DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /config
      data-cache:
        existingClaim: calibre-cache
        globalMounts:
          - path: /cache
      media:
        type: nfs
        server: "${NAS_HOST}"
        path: /data/nvme
        globalMounts: # needs to be set to nobody:nobody perms on setup of a fresh volume, because of the weird stuff s6 does, then set it to 1000:1000
          - path: /calibre-library
            subPath: media/books/ebooks
          - path: /cwa-book-ingest
            subPath: downloads/openbooks
