apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-monitoring
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets

  target:
    name: doppler-monitoring

  dataFrom:
    - extract:
        key: MONITORING_SECRETS
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
