apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: minio
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: minio-doppler-token
  managedSecret:
    name: minio-doppler-secret
    namespace: minio
