apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: various
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: various-doppler-token
  managedSecret:
    name: various-doppler-secret
    namespace: various
