---
- kubernetes:
    cluster:
      cpu: true
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- datetime:
    text_size: x1
    format:
      dateStyle: long
      timeStyle: short
      hour12: true
