apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

helmCharts:
  - name: minio
    repo: https://charts.min.io
    version: 5.0.13
    valuesFile: values.yaml
    namespace: storage
    releaseName: minio
    includeCRDs: true

resources:
  - externalsecret.yaml
  - ingressroute.yaml
