apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: drone
  namespace: argocd
spec:
  source:
    repoURL: https://git.sbbh.cloud/sysadm/homelab.git
    path: k8s/apps/gitops/drone
    targetRevision: main
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
