---
all:
  hosts:
    x1:
      ip_addr: 10.11.100.100/24
      mac_addr: ee:39:a3:7c:ce:25
    vps:
      ansible_user: debian
      ip_addr: 100.94.245.44/24
    pikvm:
      ansible_user: root
      ip_addr: 10.11.10.5/24
      mac_addr: dc:a6:32:73:9b:0f
    unifi-switch:
      ip_addr: 10.11.254.2/24
pve:
  hosts:
    pve-fw:
      ansible_user: root
      ip_addr: 10.11.10.100/24
    pve-nas:
      ansible_user: root
      ip_addr: 10.11.10.101/24
vm:
  hosts:
    opnsense:
      ip_addr: 100.87.8.30/24
    mgmt:
      ip_addr: 10.11.10.2/24
    services:
      ip_addr: 10.11.10.20/24
k8s:
  hosts:
    k8s-nuc:
      ip_addr: 10.11.80.11/24
      mac_addr: 00:00:22:50:36:46
    k8s-opti-01:
      ip_addr: 10.11.80.12/24
      mac_addr: 54:bf:64:a1:1c:00
    k8s-opti-02:
      ip_addr: 10.11.80.13/24
      mac_addr: d8:9e:f3:82:d6:59
