---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_HEARTBEAT_URL: "{{ .heartbeat_url }}"
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .pushover_user_key }}"
  dataFrom:
    - extract:
        key: ops/k8s/alertmanager
