---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

image_pull_secrets:
  - DRONE_DOCKER_CONFIG

steps:
  - name: lint
    image: git.sbbh.cloud/infra/ansible-runner:latest
    privileged: true
    commands:
      - env
      - .drone/lint.sh
    environment:
      ANSIBLE_VAULT_PASSWORD:
        from_secret: ANSIBLE_VAULT_PASSWORD

  - name: apps
    image: git.sbbh.cloud/infra/ansible-runner:latest
    commands:
      - /entry.sh .drone/apps.sh
    environment:
      ANSIBLE_VAULT_PASSWORD:
        from_secret: ANSIBLE_VAULT_PASSWORD
      DRONE_SSH_KEY:
        from_secret: DRONE_SSH_KEY
      DRONE_SSH_PUB_KEY:
        from_secret: DRONE_SSH_PUB_KEY
    when:
      status: [success]
      event: [push, custom]

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: Drone
      webhook_id:
        from_secret: DRONE_DISCORD_ID
      webhook_token:
        from_secret: DRONE_DISCORD_TOKEN
      message: >
        {{#success build.status}}✅{{else}}⚠️{{/success}}
        repo: `[{{repo.name}}/{{commit.branch}}]` `[{{uppercase build.event}}]` [[#{{build.number}}]({{build.link}})][[{{truncate commit.sha 5}}]({{commit.link}})]
               commit: `{{commit.message}}`
    when:
      status: [failure]
---
kind: secret
name: GITHUB_USER
get:
  path: doppler-drone
  name: GITHUB_USER
---
kind: secret
name: GITHUB_TOKEN
get:
  path: doppler-drone
  name: GITHUB_TOKEN
---
kind: secret
name: DOCKER_USER
get:
  path: doppler-drone
  name: DOCKER_USER
---
kind: secret
name: DOCKER_PASSWORD
get:
  path: doppler-drone
  name: DOCKER_PASSWORD
---
kind: secret
name: DRONE_DOCKER_CONFIG
get:
  path: doppler-drone
  name: DRONE_DOCKER_CONFIG
---
kind: secret
name: DRONE_DISCORD_ID
get:
  path: doppler-drone
  name: DRONE_DISCORD_ID
---
kind: secret
name: DRONE_DISCORD_TOKEN
get:
  path: doppler-drone
  name: DRONE_DISCORD_TOKEN
---
kind: secret
name: DRONE_SSH_KEY
get:
  path: doppler-drone
  name: DRONE_SSH_KEY
---
kind: secret
name: DRONE_SSH_PUB_KEY
get:
  path: doppler-drone
  name: DRONE_SSH_PUB_KEY
---
kind: secret
name: ANSIBLE_VAULT_PASSWORD
get:
  path: doppler-drone
  name: ANSIBLE_VAULT_PASSWORD
