---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

image_pull_secrets:
  - DOCKER_CONF

steps:
  - name: lint
    image: git.sbbh.cloud/sysadm/ansible-runner:latest
    privileged: true
    commands:
      - ip link set dev eth0 mtu 1450
      - .drone/lint.sh
    environment:
      ANSIBLE_VAULT_PASSWORD:
        from_secret: ANSIBLE_VAULT_PASSWORD

  - name: apps
    image: git.sbbh.cloud/sysadm/ansible-runner:latest
    commands:
      - .drone/apps.sh
    environment:
      ANSIBLE_VAULT_PASSWORD:
        from_secret: ANSIBLE_VAULT_PASSWORD
      SSH_KEY:
        from_secret: SSH_KEY
    when:
      event:
      - push

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: Drone
      webhook_id:
        from_secret: DISCORD_ID
      webhook_token:
        from_secret: DISCORD_TOKEN
      message: >
        {{#success build.status}}✅{{else}}⚠️{{/success}}
        repo: `[{{repo.name}}/{{commit.branch}}]` `[{{uppercase build.event}}]` [[#{{build.number}}]({{build.link}})][[{{truncate commit.sha 5}}]({{commit.link}})]
               commit: `{{commit.message}}`
    when:
      status: [ success, failure, changed ]
      event: [ push ]
---
kind: secret
name: DOCKER_CONF
get:
  path: doppler-drone
  name: DOCKER_CONF
---
kind: secret
name: DISCORD_ID
get:
  path: doppler-drone
  name: DISCORD_ID
---
kind: secret
name: DISCORD_TOKEN
get:
  path: doppler-drone
  name: DISCORD_TOKEN
---
kind: secret
name: ANSIBLE_VAULT_PASSWORD
get:
  path: doppler-drone
  name: ANSIBLE_VAULT_PASSWORD
---
kind: secret
name: SSH_KEY
get:
  path: doppler-drone
  name: SSH_KEY
