apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  $patch: merge
  statusbadge.enabled: "true"
  resource.customizations.ignoreDifferences.all: |
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
