---

replicas: 3

admin:
  existingSecret: doppler-monitoring
  userKey: grafanaUser
  passwordKey: grafanaPassword

# src: https://github.com/onedr0p/containers/tree/main/apps/postgres-init
extraInitContainers:
  - name: 01-init-db
    image: ghcr.io/onedr0p/postgres-init:14.9
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: doppler-monitoring

env:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: postgres-rw.default.svc.cluster.local
  GF_DATABASE_USER: grafana

envFromSecrets:
  - name: doppler-monitoring

grafana.ini:
  feature_toggles:
    enable: publicDashboards
  analytics:
    check_for_updates: false
    check_for_plugin_updates: false
  date_formats:
    use_browser_locale: true
  security:
    cookie_samesite: grafana
  server:
    root_url: https://grafana.k8s.sbbh.cloud
  plugins:
    allow_loading_unsigned_plugins: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
      - name: Alertmanager
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
      # - name: Loki
      #   type: loki
      #   access: proxy
      #   url: http://loki-gateway.monitoring.svc.cluster.local
      #   jsonData:
      #     maxLines: 250
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
        jsonData:
          implementation: prometheus

dashboards:
  default:
    # ref: https://grafana.com/grafana/dashboards/13502-minio-dashboard/
    minio:
      gnetid: 13502
      revision: 21
      datasource: Prometheus
    # ref: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
    node-exporter-full:
      gnetid: 1860
      revision: 30
      datasource: Prometheus
    cert-manager:
      url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
      datasource: Prometheus
    external-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
      datasource: Prometheus
    kubernetes-api-server:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      datasource: Prometheus
    kubernetes-coredns:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
      datasource: Prometheus
    kubernetes-global:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
      datasource: Prometheus
    kubernetes-namespaces:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
      datasource: Prometheus
    kubernetes-nodes:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
      datasource: Prometheus
    kubernetes-pods:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
      datasource: Prometheus

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: true
    searchNamespace: ALL

plugins:
  - grafana-piechart-panel
  - grafana-clock-panel
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - natel-discrete-panel
  - pr0ps-trackmap-panel
  - vonage-status-panel

serviceMonitor:
  enabled: true

persistence:
  enabled: false

testFramework:
  enabled: false
