---
autoDirectNodeRoutes: true
bpf:
  masquerade: true
  # Ref: https://github.com/siderolabs/talos/issues/10002
  hostLegacyRouting: true
  vlanBypass: [0]
# cni:
#   # Required for pairing with Multus CNI
#   exclusive: false
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
# devices: ".*"
# dashboards:
#   enabled: true
# endpointRoutes:
#   enabled: true
# envoy:
#   rollOutPods: true
#   prometheus:
#      serviceMonitor:
#        enabled: true
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
      - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  redact:
    enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: "10.42.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
# kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 1
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      #       - PERFMON
      #       - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
socketLB:
  hostNamespaceOnly: true
