apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.sbbh.cloud/sysadm/homelab.git
    targetRevision: main
    path: k8s/doppler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
