apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
spec:
  project: default
  sources:
    - chart: drone
      repoURL: https://charts.drone.io
      targetRevision: 0.6.4
      helm:
        values: |
          env:
            DRONE_SERVER_HOST: drone.k8s.sbbh.cloud
            DRONE_SERVER_PROTO: https
            DRONE_GITEA_SERVER: https://git.sbbh.cloud
            DRONE_USER_CREATE: username:sysadm,admin:true
          extraSecretNamesForEnvFrom:
            - drone-doppler-secret
    - chart: drone-runner-docker
      repoURL: https://charts.drone.io
      targetRevision: 0.6.1
      helm:
        values: |
          env:
            DRONE_RPC_HOST: drone:8080
            DRONE_RUNNER_NETWORKS: host
          extraSecretNamesForEnvFrom:
            - drone-doppler-secret
    - chart: drone-kubernetes-secrets
      repoURL: https://charts.drone.io
      targetRevision: 0.1.4
      helm:
        values: |
          extraSecretNamesForEnvFrom:
            - drone-doppler-secret
          rbac:
            secretNamespace: drone
          env:
            KUBERNETES_NAMESPACE: drone
    - repoURL: https://git.sbbh.cloud/sysadm/homelab.git
      targetRevision: main
      path: k8s/drone
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true
    #   prune: true
