resources:
  - system-app.yaml
  - argocd-app.yaml
  - doppler-app.yaml
  - cert-manager-app.yaml
  - traefik-app.yaml
  - drone-app.yaml
  - longhorn-app.yaml
  - minio-app.yaml
  - k10-app.yaml
  - monitoring-app.yaml
  - various-app.yaml
