apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://git.sbbh.cloud/sysadm/homelab.git
      targetRevision: main
      path: k8s/minio
    - chart: minio
      repoURL: https://charts.min.io
      targetRevision: 5.0.8
      helm:
        values: |
          # Get root user/password from secret
          existingSecret: minio-secret

          # Number of drives attached to a node
          drivesPerNode: 1
          # Number of MinIO containers running
          replicas: 3
          # Number of expanded MinIO clusters
          pools: 1
          # Persistence
          persistence:
            enabled: true
            storageClass: "longhorn"
            accessMode: ReadWriteOnce
            size: 10Gi

          # Resource request
          resources:
            requests:
              memory: 1Gi

          # Minio Buckets
          buckets:
            - name: k3s-loki
              policy: none

          # Minio Policies
          policies:
            - name: loki
              statements:
                - resources:
                    - 'arn:aws:s3:::k3s-loki'
                    - 'arn:aws:s3:::k3s-loki/*'
                  actions:
                    - "s3:DeleteObject"
                    - "s3:GetObject"
                    - "s3:ListBucket"
                    - "s3:PutObject"
          # Minio Users
          users:
            - accessKey: loki
              existingSecret: minio-secret 
              existingSecretKey: lokiPassword
              policy: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true
    #   prune: true
