apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.8.1
      helm:
        values: |
          fullnameOverride: prometheus

          alertmanager:
            fullnameOverride: alertmanager

          grafana:
            fullnameOverride: grafana
            defaultDashboardsTimezone: Australia/Melbourne
            admin:
              existingSecret: monitoring-doppler-secret
              userKey: GRAFANA_USER
              passwordKey: GRAFANA_PASSWORD
            additionalDataSources:
              - name: Loki
                type: loki
                url: http://logging-loki-distributed-query-frontend.logging:3100
            persistence:
              type: pvc
              enabled: true
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              size: 10Gi

          kubelet:
            enabled: true
            serviceMonitor:
              metricRelabelings:
                - action: replace
                  sourceLabels:
                    - node
                  targetLabel: instance

          kubeControllerManager:
            enabled: true
            endpoints: # ips of servers
              - 10.0.10.81
              - 10.0.10.82
              - 10.0.10.83

          kubeEtcd:
            endpoints:
              - 10.0.10.81
              - 10.0.10.82
              - 10.0.10.83

          kubeScheduler:
            endpoints:
              - 10.0.10.81
              - 10.0.10.82
              - 10.0.10.83

          kubeProxy:
            endpoints:
              - 10.0.10.81
              - 10.0.10.82
              - 10.0.10.83

          kube-state-metrics:
            fullnameOverride: kube-state-metrics
            selfMonitor:
              enabled: true
            prometheus:
              monitor:
                enabled: true
                relabelings:
                  - action: replace
                    regex: (.*)
                    replacement: $1
                    sourceLabels:
                      - __meta_kubernetes_pod_node_name
                    targetLabel: kubernetes_node

          nodeExporter:
            serviceMonitor:
              relabelings:
                - action: replace
                  regex: (.*)
                  replacement: $1
                  sourceLabels:
                    - __meta_kubernetes_pod_node_name
                  targetLabel: kubernetes_node

          prometheus-node-exporter:
            fullnameOverride: node-exporter
            prometheus:
              monitor:
                relabelings:
                  - action: replace
                    regex: (.*)
                    replacement: $1
                    sourceLabels:
                      - __meta_kubernetes_pod_node_name
                    targetLabel: kubernetes_node
            resources:
              requests:
                memory: 512Mi
                cpu: 250m
              limits:
                memory: 2048Mi

          prometheus:
            prometheusSpec:
              replicaExternalLabelName: "replica"
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              probeSelectorNilUsesHelmValues: false
              retention: 6h
              enableAdminAPI: true
    - repoURL: https://git.sbbh.cloud/sysadm/homelab.git
      targetRevision: main
      path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
