apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone

helmCharts:
- name: drone-kubernetes-secrets
  namespace: drone
  repo: https://charts.drone.io
  valuesFile: values.yaml
  version: 0.1.4
  includeCRDs: true
  releaseName: drone-kubernetes-secrets
