---
- name: Pull kube-vip image and create manifest
  ansible.builtin.shell: |
    set -eo pipefail
    ctr image pull ghcr.io/kube-vip/kube-vip:{{ k8s.vip.version }}
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:{{ k8s.vip.version }} vip /kube-vip manifest pod \
    --interface {{ k8s.vip.iface }} \
    --address {{ k8s.vip.ip }} \
    --controlplane \
    --services \
    --arp \
    --leaderElection | tee  /etc/kubernetes/manifests/kube-vip.yaml
