---
- name: Install Helm
  ansible.builtin.shell: |
    curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Install Kustomize
  ansible.builtin.shell: |
    pushd /usr/local/bin
    curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
  args:
    creates: /usr/local/bin/kustomize

- name: Install ksops
  ansible.builtin.shell: |
    curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh | bash
  args:
    creates: /usr/local/bin/ksops

- name: Create plugins directory
  ansible.builtin.file:
    path: /root/.config/kustomize/plugin/viaduct.ai/v1/ksops
    state: directory
    mode: "0755"

- name: Link ksops binary to plugins directory
  ansible.builtin.file:
    src: /usr/local/bin/ksops
    dest: /root/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
    state: hard
