---
libraries:
  Movies:
    overlay_files:
      - remove_overlays: false
      - default: ribbon

  TV Shows:
    overlay_files:
      - remove_overlays: false
      - default: ribbon

settings:
  sync_mode: sync
  show_missing: false
  show_missing_assets: false
  # custom_repo: https://github.com/Subbeh/homelab/tree/main/k8s/apps/media/plex/kometa/custom/

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

plex:
  url: http://plex:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

radarr:
  url: http://radarr
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /media/movies
  monitor: true
  availability: announced
  quality_profile: HD
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false

sonarr:
  url: http://sonarr
  token: <<SONARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /media/tv
  monitor: all
  quality_profile: HD
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:
