apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: gitops
data:
  $patch: merge
  statusbadge.enabled: "true"
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
