# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: homelab

talosVersion: ${talosVersion}
kubernetesVersion: ${kubernetesVersion}

endpoint: https://10.11.80.100:6443
additionalApiServerCertSans: &sans
  - 127.0.0.1
additionalMachineCertSans: *sans

clusterPodNets: [10.42.0.0/16]
clusterSvcNets: [10.43.0.0/16]

nodes:
  - hostname: k8s-nuc
    ipAddress: 10.11.80.11
    installDisk: /dev/nvme0n1
    machineSpec:
      secureboot: false
    talosImageURL: &talosImageURL factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 00:00:22:50:36:46
        dhcp: false
        addresses:
          - 10.11.80.11/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.11.80.1
        mtu: 1500
        vip:
          ip: 10.11.80.100
      - deviceSelector:
          hardwareAddr: 48:21:0b:55:89:ab
        dhcp: false
        addresses:
          - 192.168.80.11/24
        routes:
          - network: 192.168.80.0/24
        mtu: 1500
  - hostname: k8s-opti-01
    ipAddress: 10.11.80.12
    installDisk: /dev/nvme0n1
    machineSpec:
      secureboot: false
    talosImageURL: *talosImageURL
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 54:bf:64:a1:1c:00
        dhcp: false
        addresses:
          - 10.11.80.12/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.11.80.1
        mtu: 1500
        vip:
          ip: 10.11.80.100
      - deviceSelector:
          hardwareAddr: 02:26:25:02:06:43
        dhcp: false
        addresses:
          - 192.168.80.12/24
        routes:
          - network: 192.168.80.0/24
        mtu: 1500
  - hostname: k8s-opti-02
    ipAddress: 10.11.80.13
    installDisk: /dev/nvme0n1
    machineSpec:
      secureboot: false
    talosImageURL: *talosImageURL
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: d8:9e:f3:82:d6:59
        dhcp: false
        addresses:
          - 10.11.80.13/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.11.80.1
        mtu: 1500
        vip:
          ip: 10.11.80.100
      - deviceSelector:
          hardwareAddr: 02:26:25:02:06:51
        dhcp: false
        addresses:
          - 192.168.80.13/24
        routes:
          - network: 192.168.80.0/24
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/cluster-crds.yaml"
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kernelargs.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-modules.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-udev.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
