---
- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ k8s.kubeconfig_loc }}"
    flat: yes

- name: Set file permissions
  ansible.builtin.file:
    path: "{{ k8s.kubeconfig_loc }}"
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: "0600"
  delegate_to: localhost
  become: false
