---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app audiobookshelf
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
    - ../../../../components/keda/nfs-scaler
  dependsOn:
    - name: keda
      namespace: observability
    - name: storage-ready
      namespace: flux-system
  interval: 1h
  retryInterval: 2m
  path: ./k8s/apps/media/audiobookshelf/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      GATUS_GROUP: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
