---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iperf3
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      iperf3:
        type: daemonset
        containers:
          server:
            image:
              repository: networkstatic/iperf3
              tag: latest
            command: ["iperf3"]
            args: ["-s", "-p", "5201"]
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 5201
                  initialDelaySeconds: 10
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 5201
                  initialDelaySeconds: 5
                  periodSeconds: 10
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 5201
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: 
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
          client:
            image:
              repository: networkstatic/iperf3
              tag: latest
            command: ["sleep"]
            args: ["infinity"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 200m
                memory: 128Mi
    defaultPodOptions:
      hostNetwork: true
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
    service:
      app:
        controller: iperf3
        ports:
          tcp:
            port: 5201
            protocol: TCP
          udp:
            port: 5201
            protocol: UDP
