---
http:
  middlewares:
    chain-internal:
      chain:
        middlewares:
          - local-whitelist

    chain-external:
      chain:
        middlewares:
          - cloudflarewarp
          - crowdsec
          - rate-limit
          - secure-headers
          - compress
          - authentik

    chain-external-no-auth:
      chain:
        middlewares:
          - cloudflarewarp
          - crowdsec
          - rate-limit
          - secure-headers
          - compress
