---

http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - secure-headers
          - compress

    chain-auth:
      chain:
        middlewares:
          - crowdsec-bouncer
          - rate-limit
          - secure-headers
          - compress
          - authentik
