apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 46.4.1
    namespace: monitoring
    valuesFile: values.yaml
    releaseName: kube-prometheus-stack
    includeCRDs: true

resources:
  - namespace.yaml
  - externalsecret.yaml
  - ingressroute.yaml
  - config/service-metric-k3s.yaml
  - config/rule-k3s.yaml
  - config/servicemonitor.yaml
  - config/servicemonitor-traefik.yaml

  - dashboards/cm-api-server-dashboard.yaml
  - dashboards/cm-controller-manager-dashboard.yaml
  - dashboards/cm-etcd-dashboard.yaml
  - dashboards/cm-kubelet-dashboard.yaml
  - dashboards/cm-proxy-dashboard.yaml
  - dashboards/cm-scheduler-dashboard.yaml
